In [1]:
import pandas as pd

In [2]:
import pandas as pd

data = {
    'student': ['Aarav', 'Sneha', 'Ranjit', 'Priya', 'Karan', 'Anjali', 'Dev', 'Meera', 'Rohan', 'Tanvi'],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai'],
    'marks': [88, 45, 72, 91, 55, 78, 60, 83, 47, 69],
    'attendance': [95, 60, 80, 98, 55, 88, 72, 91, 50, 75],
    'passed': [True, False, True, True, False, True, True, True, False, True]
}
df = pd.DataFrame(data)
df

  student  gender    city  marks  attendance  passed
0   Aarav    Male    Pune     88          95    True
1   Sneha  Female  Mumbai     45          60   False
2  Ranjit    Male   Delhi     72          80    True
3   Priya  Female    Pune     91          98    True
4   Karan    Male  Nagpur     55          55   False
5  Anjali  Female  Mumbai     78          88    True
6     Dev    Male   Delhi     60          72    True
7   Meera  Female    Pune     83          91    True
8   Rohan    Male  Nagpur     47          50   False
9   Tanvi  Female  Mumbai     69          75    True

## **1. How many students passed and failed?**

In [6]:
df["passed"].value_counts()

passed
True     7
False    3
Name: count, dtype: int64

## **What is the average marks of male vs female students?**

In [28]:
df.groupby("gender")["marks"].mean()

gender
Female    73.2
Male      64.4
Name: marks, dtype: float64

## **3. Which city has the highest average attendance?**

In [33]:
df.groupby("city")["attendance"].mean().idxmax()

'Pune'

## 4.**Filter students from Pune or Mumbai who passed**

In [39]:
df[df["city"].isin(["Pune", "Mumbai"]) & (df["passed"] == True)]

  student  gender    city  marks  attendance  passed
0   Aarav    Male    Pune     88          95    True
3   Priya  Female    Pune     91          98    True
5  Anjali  Female  Mumbai     78          88    True
7   Meera  Female    Pune     83          91    True
9   Tanvi  Female  Mumbai     69          75    True

## **5.Filter students whose name contains 'an' and marks above 60**

In [41]:
df[df["student"].str.contains("an") & (df["marks"] > 60)]

  student  gender    city  marks  attendance  passed
2  Ranjit    Male   Delhi     72          80    True
9   Tanvi  Female  Mumbai     69          75    True