In [1]:
import pandas as pd

In [2]:
data = {
    'product': ['Laptop', 'Phone', 'Tablet', 'Watch', 'Earbuds', 'Monitor', 'Keyboard', 'Mouse', 'Charger', 'Speaker'],
    'category': ['Electronics', 'Electronics', 'Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories', 'Accessories', 'Accessories', 'Electronics'],
    'brand': ['Dell', 'Samsung', 'Apple', 'Fossil', 'Sony', 'LG', 'Logitech', 'Logitech', 'Anker', 'Sony'],
    'price': [75000, 25000, 60000, 15000, 8000, 20000, 3000, 1500, 2000, 12000],
    'rating': [4.5, 4.2, 4.8, 3.9, 4.1, 4.3, 3.7, 4.6, 4.0, 4.4],
    'stock': [10, 0, 5, 8, 0, 3, 15, 20, 25, 7]
}
df = pd.DataFrame(data)
df

    product     category     brand  price  rating  stock
0    Laptop  Electronics      Dell  75000     4.5     10
1     Phone  Electronics   Samsung  25000     4.2      0
2    Tablet  Electronics     Apple  60000     4.8      5
3     Watch  Accessories    Fossil  15000     3.9      8
4   Earbuds  Accessories      Sony   8000     4.1      0
5   Monitor  Electronics        LG  20000     4.3      3
6  Keyboard  Accessories  Logitech   3000     3.7     15
7     Mouse  Accessories  Logitech   1500     4.6     20
8   Charger  Accessories     Anker   2000     4.0     25
9   Speaker  Electronics      Sony  12000     4.4      7

5 Questions:
How many products are in each category?
What is average price by brand?
Which product has the highest rating?
Filter products from Sony or Apple that are in stock
Filter products NOT in Accessories with price above 10000

## **1.How many products are in each category?**

In [10]:
df.groupby("category")["product"].count()

category
Accessories    5
Electronics    5
Name: product, dtype: int64

## **2.What is average price by brand?**

In [11]:
df.groupby("brand")["price"].mean()

brand
Anker        2000.0
Apple       60000.0
Dell        75000.0
Fossil      15000.0
LG          20000.0
Logitech     2250.0
Samsung     25000.0
Sony        10000.0
Name: price, dtype: float64

## **3.Which product has the highest rating?**

In [20]:
df["rating"].max()

4.8

## **4.Filter products from Sony or Apple that are in stock?**

In [27]:
df[df["brand"].isin(["Sony","Apple"]) & (df["stock"] > 0)]

   product     category  brand  price  rating  stock
2   Tablet  Electronics  Apple  60000     4.8      5
9  Speaker  Electronics   Sony  12000     4.4      7

## **5.Filter products NOT in Accessories with price above 10000?**

In [31]:
df[~df["category"].isin(["Accessories"]) & (df["price"] > 10000)]

   product     category    brand  price  rating  stock
0   Laptop  Electronics     Dell  75000     4.5     10
1    Phone  Electronics  Samsung  25000     4.2      0
2   Tablet  Electronics    Apple  60000     4.8      5
5  Monitor  Electronics       LG  20000     4.3      3
9  Speaker  Electronics     Sony  12000     4.4      7