In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

### ****To Access Only Columns****

In [3]:
df['Actor']

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [4]:
df['Actor'][5]

'Ayushmann Khurrana'

In [5]:
type(df['Actor'])

pandas.core.series.Series

In [6]:
df[['Actor','IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [7]:
df  #original dataframe is not changing

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## 1. .LOC AND .ILOC
- ****.loc**** is used for labels it gives ouput based pn labels.
- ****.iloc**** is used with indexes it givees outputs based on index.

In [8]:
df.loc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [9]:
df.loc[0]

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [10]:
df.iloc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [11]:
df.loc[0:2 , ["Actor" , "IMDb" , "Film"]]   #2 is inclusive in .loc

            Actor  IMDb             Film
0  Shah Rukh Khan   7.2          Pathaan
1     Salman Khan   6.0  Tiger Zinda Hai
2      Aamir Khan   8.4           Dangal

In [12]:
df.iloc[0:2 , [ 0 , 5]]  #2 is exclusive

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0

## Fast access using .at and .iat

In [13]:
df.at[0 , "Actor"]

'Shah Rukh Khan'

In [14]:
df.iat[0,0]

'Shah Rukh Khan'

## Filtering with conditions

In [15]:
df[df["BoxOffice(INR Crore)"] > 400]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5

In [16]:
df[df["Year"] > 2018]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [17]:
df[(df["Genre"] == "Action") & (df["IMDb"] > 7) & (df["BoxOffice(INR Crore)"] > 400)]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

## Question:
- Filter movies that satisfy EITHER of the following:
- Condition A:
- **Genre** is **Horror Comedy**
- **IMDb rating** is **greater than 6**
- OR
- Condition B:
- **BoxOffice(INR Crore) is more than 500**

In [18]:
df[(df["Genre"] == "Horror Comedy") & (df["IMDb"] > 6) | (df["BoxOffice(INR Crore)"] > 500)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5

In [19]:
# cleaner code for the same task
df[
    (
        (df["Genre"] == "Horror Comedy") &
        (df["IMDb"] > 6)
    )
    |
    (df["BoxOffice(INR Crore)"] > 500)
][["Actor", "Film", "Genre", "IMDb", "BoxOffice(INR Crore)"]]

            Actor             Film          Genre  IMDb  BoxOffice(INR Crore)
0  Shah Rukh Khan          Pathaan         Action   7.2                  1050
1     Salman Khan  Tiger Zinda Hai         Action   6.0                   565
2      Aamir Khan           Dangal      Biography   8.4                  2024
4   Ranveer Singh        Padmaavat     Historical   7.0                   585
6   Rajkummar Rao            Stree  Horror Comedy   7.5                   180

## df.query()

In [20]:
df.query("Year > 2018 and IMDb > 6")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

1️⃣ IMDb > 7.5
2️⃣ Horror Comedy movies
3️⃣ Movies after 2018 with BoxOffice > 300

In [22]:
# 1
df.query("IMDb > 7.5")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [32]:
# 2
df.query("Genre == 'Horror Comedy'")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [35]:
# 3
df.query("Year > 2018 and `BoxOffice(INR Crore)` > 300")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [36]:
# 4
df.query("IMDb >= 7")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [38]:
# 5 Show Action movies released after 2018
df.query("Genre == 'Action' and Year > 2018")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [40]:
# 6 Show movies with BoxOffice > 400 and IMDb > 6.5
df.query("`BoxOffice(INR Crore)` > 400 and IMDb > 6.5")

            Actor       Film  Year       Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan    Pathaan  2023      Action                  1050   7.2
2      Aamir Khan     Dangal  2016   Biography                  2024   8.4
4   Ranveer Singh  Padmaavat  2018  Historical                   585   7.0