In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [5]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees , departments ,on = "DeptID")        #Inner Join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

# *Left Join* 
- **JO BHI EMP TABLE KE ROWS HAI WO SAB AYENGE AND MATHCHING FROM DEPT TABLE**

In [9]:
pd.merge(employees , departments , on="DeptID",how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

## *Right Join*
- **jo right table hai uske sare records de do and jo emp me available nhi hai usko nan return kro**

In [11]:
pd.merge(employees , departments , on="DeptID" , how = "right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

## outer join
- **sare dept id's mil jayenge and jo empty hoga waha pe nan aa jayega**

In [13]:
pd.merge(employees , departments , on="DeptID" , how = "outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [14]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

In [15]:
df1

    Name
0  Alice
1    Bob

In [16]:
df2

      Name
0  Charlie
1    David

In [23]:
# wide concatenation
pd.concat([df1 , df2])  # --> new rows is formed

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [24]:
# wide concatenation  
pd.concat([df1,df2],axis=1)  # --> new columns is formed

    Name     Name
0  Alice  Charlie
1    Bob    David