In [2]:
import pandas as pd

In [12]:
df = pd.read_csv("hospital_appointments.csv")
df

,Patient_ID,Patient_Name,Gender,DOB,Appointment_Date,Department,Doctor,Fee
0,101,Rahul Sharma,Male,15/03/2000,2025-07-20,Cardiology,Dr. Mehta,₹500
1,102,Priya Patil,Female,2001-08-12,21/07/2025,Neurology,Dr. Shah,₹700
2,103,Amit Kumar,M,March 5 1999,22-Jul-2025,Orthopedics,Dr. Rao,₹600
3,104,Neha Joshi,Female,05-04-98,20250723,Pediatrics,Dr. Singh,₹450
4,105,Rohan Gupta,Male,1997/11/18,24 March 2025,Dermatology,Dr. Patel,₹550
5,106,Sneha Kulkarni,Female,Not Available,25/07/2025,Cardiology,Dr. Mehta,₹500
6,107,Vikas More,Male,31/02/2001,2025-07-26,Neurology,Dr. Shah,₹700
7,108,Pooja Desai,Female,NaN,27-07-2025,Orthopedics,Dr. Rao,₹600
8,109,Arjun Patil,Male,12.09.2002,July 28 2025,Pediatrics,Dr. Singh,₹450
9,110,Kiran Naik,Female,18/10/2001,2025/07/29,Dermatology,Dr. Patel,₹550
10,110,Kiran Naik,Female,18/10/2001,2025/07/29,Dermatology,Dr. Patel,₹550

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Patient_ID        11 non-null     int64
 1   Patient_Name      11 non-null     str
 2   Gender            11 non-null     str
 3   DOB               10 non-null     str
 4   Appointment_Date  11 non-null     str
 5   Department        11 non-null     str
 6   Doctor            11 non-null     str
 7   Fee               11 non-null     str
dtypes: int64(1), str(7)
memory usage: 1.5 KB

## **DATA CLEANING**

#### **1.Fixing Date**

In [13]:
df['DOB'] = pd.to_datetime(df['DOB'] , errors = "coerce" , format = 'mixed')
df

,Patient_ID,Patient_Name,Gender,DOB,Appointment_Date,Department,Doctor,Fee
0,101,Rahul Sharma,Male,2000-03-15,2025-07-20,Cardiology,Dr. Mehta,₹500
1,102,Priya Patil,Female,2001-08-12,21/07/2025,Neurology,Dr. Shah,₹700
2,103,Amit Kumar,M,1999-03-05,22-Jul-2025,Orthopedics,Dr. Rao,₹600
3,104,Neha Joshi,Female,1998-05-04,20250723,Pediatrics,Dr. Singh,₹450
4,105,Rohan Gupta,Male,1997-11-18,24 March 2025,Dermatology,Dr. Patel,₹550
5,106,Sneha Kulkarni,Female,NaT,25/07/2025,Cardiology,Dr. Mehta,₹500
6,107,Vikas More,Male,NaT,2025-07-26,Neurology,Dr. Shah,₹700
7,108,Pooja Desai,Female,NaT,27-07-2025,Orthopedics,Dr. Rao,₹600
8,109,Arjun Patil,Male,2002-12-09,July 28 2025,Pediatrics,Dr. Singh,₹450
9,110,Kiran Naik,Female,2001-10-18,2025/07/29,Dermatology,Dr. Patel,₹550
10,110,Kiran Naik,Female,2001-10-18,2025/07/29,Dermatology,Dr. Patel,₹550

In [17]:
df['Appointment_Date'] = pd.to_datetime(df['Appointment_Date'] , errors = 'coerce' , format = 'mixed')
df

,Patient_ID,Patient_Name,Gender,DOB,Appointment_Date,Department,Doctor,Fee
0,101,Rahul Sharma,Male,2000-03-15,2025-07-20,Cardiology,Dr. Mehta,₹500
1,102,Priya Patil,Female,2001-08-12,2025-07-21,Neurology,Dr. Shah,₹700
2,103,Amit Kumar,M,1999-03-05,2025-07-22,Orthopedics,Dr. Rao,₹600
3,104,Neha Joshi,Female,1998-05-04,2025-07-23,Pediatrics,Dr. Singh,₹450
4,105,Rohan Gupta,Male,1997-11-18,2025-03-24,Dermatology,Dr. Patel,₹550
5,106,Sneha Kulkarni,Female,NaT,2025-07-25,Cardiology,Dr. Mehta,₹500
6,107,Vikas More,Male,NaT,2025-07-26,Neurology,Dr. Shah,₹700
7,108,Pooja Desai,Female,NaT,2025-07-27,Orthopedics,Dr. Rao,₹600
8,109,Arjun Patil,Male,2002-12-09,2025-07-28,Pediatrics,Dr. Singh,₹450
9,110,Kiran Naik,Female,2001-10-18,2025-07-29,Dermatology,Dr. Patel,₹550
10,110,Kiran Naik,Female,2001-10-18,2025-07-29,Dermatology,Dr. Patel,₹550

#### **2.Removing Duplicates**

In [19]:
df.drop_duplicates(inplace=True)
df

,Patient_ID,Patient_Name,Gender,DOB,Appointment_Date,Department,Doctor,Fee
0,101,Rahul Sharma,Male,2000-03-15,2025-07-20,Cardiology,Dr. Mehta,₹500
1,102,Priya Patil,Female,2001-08-12,2025-07-21,Neurology,Dr. Shah,₹700
2,103,Amit Kumar,M,1999-03-05,2025-07-22,Orthopedics,Dr. Rao,₹600
3,104,Neha Joshi,Female,1998-05-04,2025-07-23,Pediatrics,Dr. Singh,₹450
4,105,Rohan Gupta,Male,1997-11-18,2025-03-24,Dermatology,Dr. Patel,₹550
5,106,Sneha Kulkarni,Female,NaT,2025-07-25,Cardiology,Dr. Mehta,₹500
6,107,Vikas More,Male,NaT,2025-07-26,Neurology,Dr. Shah,₹700
7,108,Pooja Desai,Female,NaT,2025-07-27,Orthopedics,Dr. Rao,₹600
8,109,Arjun Patil,Male,2002-12-09,2025-07-28,Pediatrics,Dr. Singh,₹450
9,110,Kiran Naik,Female,2001-10-18,2025-07-29,Dermatology,Dr. Patel,₹550

In [20]:
df['Gender'] = df['Gender'].replace({'M' : 'Male'})
df

,Patient_ID,Patient_Name,Gender,DOB,Appointment_Date,Department,Doctor,Fee
0,101,Rahul Sharma,Male,2000-03-15,2025-07-20,Cardiology,Dr. Mehta,₹500
1,102,Priya Patil,Female,2001-08-12,2025-07-21,Neurology,Dr. Shah,₹700
2,103,Amit Kumar,Male,1999-03-05,2025-07-22,Orthopedics,Dr. Rao,₹600
3,104,Neha Joshi,Female,1998-05-04,2025-07-23,Pediatrics,Dr. Singh,₹450
4,105,Rohan Gupta,Male,1997-11-18,2025-03-24,Dermatology,Dr. Patel,₹550
5,106,Sneha Kulkarni,Female,NaT,2025-07-25,Cardiology,Dr. Mehta,₹500
6,107,Vikas More,Male,NaT,2025-07-26,Neurology,Dr. Shah,₹700
7,108,Pooja Desai,Female,NaT,2025-07-27,Orthopedics,Dr. Rao,₹600
8,109,Arjun Patil,Male,2002-12-09,2025-07-28,Pediatrics,Dr. Singh,₹450
9,110,Kiran Naik,Female,2001-10-18,2025-07-29,Dermatology,Dr. Patel,₹550

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Patient_ID        10 non-null     int64
 1   Patient_Name      10 non-null     str
 2   Gender            10 non-null     str
 3   DOB               7 non-null      datetime64[us]
 4   Appointment_Date  10 non-null     datetime64[us]
 5   Department        10 non-null     str
 6   Doctor            10 non-null     str
 7   Fee               10 non-null     str
dtypes: datetime64[us](2), int64(1), str(5)
memory usage: 1.2 KB

#### **3.Fixing Fee Column**

In [ ]:
# changing data type from str to int

In [25]:
df["Fee"] = df["Fee"].str.replace("₹", "", regex=False).astype(int)
df

,Patient_ID,Patient_Name,Gender,DOB,Appointment_Date,Department,Doctor,Fee
0,101,Rahul Sharma,Male,2000-03-15,2025-07-20,Cardiology,Dr. Mehta,500
1,102,Priya Patil,Female,2001-08-12,2025-07-21,Neurology,Dr. Shah,700
2,103,Amit Kumar,Male,1999-03-05,2025-07-22,Orthopedics,Dr. Rao,600
3,104,Neha Joshi,Female,1998-05-04,2025-07-23,Pediatrics,Dr. Singh,450
4,105,Rohan Gupta,Male,1997-11-18,2025-03-24,Dermatology,Dr. Patel,550
5,106,Sneha Kulkarni,Female,NaT,2025-07-25,Cardiology,Dr. Mehta,500
6,107,Vikas More,Male,NaT,2025-07-26,Neurology,Dr. Shah,700
7,108,Pooja Desai,Female,NaT,2025-07-27,Orthopedics,Dr. Rao,600
8,109,Arjun Patil,Male,2002-12-09,2025-07-28,Pediatrics,Dr. Singh,450
9,110,Kiran Naik,Female,2001-10-18,2025-07-29,Dermatology,Dr. Patel,550

In [26]:
df.to_csv("hospital_appointments_cleaned.csv", index=False)