In [1]:
import pandas as pd

data = {
    'employee': ['Riya', 'Anand', 'Karan', 'Tanvi', 'Dev', 'Anjali', 'Rohan', 'Sneha', 'Arjun', 'Meera'],
    'department': ['Tech', 'HR', 'Finance', 'Tech', 'HR', 'Finance', 'Tech', 'HR', 'Finance', 'Tech'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Nagpur', 'Pune', 'Mumbai', 'Delhi', 'Nagpur', 'Pune', 'Mumbai'],
    'salary': [75000, 30000, 45000, 80000, 32000, 50000, 70000, 28000, 55000, 85000],
    'experience': [3, 1, 4, 5, 2, 3, 4, 1, 6, 7],
    'rating': [4.5, 3.2, 4.0, 4.8, 3.5, 4.1, 4.3, 3.0, 4.6, 4.9]
}
df = pd.DataFrame(data)
df

  employee department    city  salary  experience  rating
0     Riya       Tech    Pune   75000           3     4.5
1    Anand         HR  Mumbai   30000           1     3.2
2    Karan    Finance   Delhi   45000           4     4.0
3    Tanvi       Tech  Nagpur   80000           5     4.8
4      Dev         HR    Pune   32000           2     3.5
5   Anjali    Finance  Mumbai   50000           3     4.1
6    Rohan       Tech   Delhi   70000           4     4.3
7    Sneha         HR  Nagpur   28000           1     3.0
8    Arjun    Finance    Pune   55000           6     4.6
9    Meera       Tech  Mumbai   85000           7     4.9

5 Questions:
Count employees in each department
Average salary by city
Which employee has the highest rating?
Filter employees from Tech or Finance with salary above 60000
Filter employees with experience between 3 and 6 who are NOT from HR

## **1.Count employees in each department**

In [3]:
df.groupby("department")["employee"].count()

department
Finance    3
HR         3
Tech       4
Name: employee, dtype: int64

## **2.Average salary by city**

In [4]:
df.groupby("city")["salary"].mean()

city
Delhi     57500.0
Mumbai    55000.0
Nagpur    54000.0
Pune      54000.0
Name: salary, dtype: float64

## **3.Which employee has the highest rating?**

In [6]:
df.loc[df["rating"].idxmax() , "employee"]

'Meera'

## **4.Filter employees from Tech or Finance with salary above 60000**

In [7]:
df[df["department"].isin(["Tech","Finance"]) & (df["salary"] > 60000)]

  employee department    city  salary  experience  rating
0     Riya       Tech    Pune   75000           3     4.5
3    Tanvi       Tech  Nagpur   80000           5     4.8
6    Rohan       Tech   Delhi   70000           4     4.3
9    Meera       Tech  Mumbai   85000           7     4.9

## **5.Filter employees with experience between 3 and 6 who are NOT from HR**

In [9]:
df[~df["department"].isin(["HR"]) & (df["experience"].between(3,6))]

  employee department    city  salary  experience  rating
0     Riya       Tech    Pune   75000           3     4.5
2    Karan    Finance   Delhi   45000           4     4.0
3    Tanvi       Tech  Nagpur   80000           5     4.8
5   Anjali    Finance  Mumbai   50000           3     4.1
6    Rohan       Tech   Delhi   70000           4     4.3
8    Arjun    Finance    Pune   55000           6     4.6