In [2]:
import pandas as pd

data = {
    'name': ['Aarav', 'Sneha', 'Rahul', 'Priya', 'Karan', 'Mehta', 'Divya', 'Rohan'],
    'age': [22, 25, 19, 30, 21, 28, 24, 35],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Pune', 'Mumbai'],
    'salary': [25000, 45000, 20000, 60000, 22000, 50000, 35000, 70000],
    'experience': [1, 3, 0, 6, 1, 4, 2, 8]
}

df = pd.DataFrame(data)
df

    name  age    city  salary  experience
0  Aarav   22    Pune   25000           1
1  Sneha   25  Mumbai   45000           3
2  Rahul   19   Delhi   20000           0
3  Priya   30    Pune   60000           6
4  Karan   21  Mumbai   22000           1
5  Mehta   28   Delhi   50000           4
6  Divya   24    Pune   35000           2
7  Rohan   35  Mumbai   70000           8

3 Filtering Tasks:

Filter all employees from Pune with salary greater than 30000
Filter employees whose age is between 20 and 26 (inclusive)
Filter employees with experience greater than 2 and city is not Delhi

In [5]:
#1 
df[(df["city"] == "Pune") & (df["salary"] > 30000)]

    name  age  city  salary  experience
3  Priya   30  Pune   60000           6
6  Divya   24  Pune   35000           2

In [10]:
#2
df[df[ 20 <= ["age"] <= 26]]

TypeError: '<=' not supported between instances of 'int' and 'list'

In [13]:
#3
df[(df["experience"] > 2) & (df["city"] != "Delhi")]

    name  age    city  salary  experience
1  Sneha   25  Mumbai   45000           3
3  Priya   30    Pune   60000           6
7  Rohan   35  Mumbai   70000           8

In [14]:
# Option A — using &
df[(df["age"] >= 20) & (df["age"] <= 26)]

    name  age    city  salary  experience
0  Aarav   22    Pune   25000           1
1  Sneha   25  Mumbai   45000           3
4  Karan   21  Mumbai   22000           1
6  Divya   24    Pune   35000           2

In [15]:
# Option B — using .between():
df[df["age"].between(20, 26)]

    name  age    city  salary  experience
0  Aarav   22    Pune   25000           1
1  Sneha   25  Mumbai   45000           3
4  Karan   21  Mumbai   22000           1
6  Divya   24    Pune   35000           2