In [1]:
import pandas as pd

1. .isin() → filter multiple values cleanly
df[df['city'].isin(['Mumbai', 'Pune', 'Delhi'])]
Instead of writing 3 OR conditions!

2. .str.contains() → filter by partial text
df[df['name'].str.contains('an')]
Finds all names that contain "an" anywhere!

3. ~ (tilde) → NOT operator
df[~df['city'].isin(['Mumbai', 'Pune'])]
Gives everything EXCEPT Mumbai and Pune!

In [3]:
data = {
    'name': ['Aarav', 'Sneha', 'Ranjeet', 'Priya', 'Karan', 'Ankit', 'Divya', 'Rohan'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai', 'Delhi', 'Nagpur'],
    'department': ['HR', 'Tech', 'Finance', 'Tech', 'HR', 'Finance', 'Tech', 'HR'],
    'salary': [30000, 75000, 45000, 68000, 32000, 50000, 80000, 28000]
}
df = pd.DataFrame(data)
df

      name    city department  salary
0    Aarav    Pune         HR   30000
1    Sneha  Mumbai       Tech   75000
2  Ranjeet   Delhi    Finance   45000
3    Priya    Pune       Tech   68000
4    Karan  Nagpur         HR   32000
5    Ankit  Mumbai    Finance   50000
6    Divya   Delhi       Tech   80000
7    Rohan  Nagpur         HR   28000

3 Tasks:
Filter employees from Pune, Mumbai or Nagpur using .isin()
Filter employees whose name contains 'an' using .str.contains()
Filter employees who are NOT in Tech or Finance using ~ and .isin()

In [4]:
df[df["city"].isin(["Mumbai" , "Pune" , "Nagpur"])]

    name    city department  salary
0  Aarav    Pune         HR   30000
1  Sneha  Mumbai       Tech   75000
3  Priya    Pune       Tech   68000
4  Karan  Nagpur         HR   32000
5  Ankit  Mumbai    Finance   50000
7  Rohan  Nagpur         HR   28000

In [5]:
df[df["name"].str.contains("an")]

      name    city department  salary
2  Ranjeet   Delhi    Finance   45000
4    Karan  Nagpur         HR   32000
7    Rohan  Nagpur         HR   28000

In [6]:
df[~df["department"].isin(["Tech","Finance"])]

    name    city department  salary
0  Aarav    Pune         HR   30000
4  Karan  Nagpur         HR   32000
7  Rohan  Nagpur         HR   28000

In [7]:
data = {
    'student': ['Aarav', 'Ananya', 'Ranjit', 'Priya', 'Karan', 'Anjali', 'Dev', 'Sneha'],
    'city': ['Pune', 'Mumbai', 'Nagpur', 'Delhi', 'Pune', 'Mumbai', 'Nagpur', 'Delhi'],
    'stream': ['Science', 'Commerce', 'Arts', 'Science', 'Commerce', 'Science', 'Arts', 'Commerce'],
    'marks': [88, 55, 42, 91, 67, 78, 50, 83],
    'passed': [True, True, False, True, True, True, False, True]
}
df = pd.DataFrame(data)
df

  student    city    stream  marks  passed
0   Aarav    Pune   Science     88    True
1  Ananya  Mumbai  Commerce     55    True
2  Ranjit  Nagpur      Arts     42   False
3   Priya   Delhi   Science     91    True
4   Karan    Pune  Commerce     67    True
5  Anjali  Mumbai   Science     78    True
6     Dev  Nagpur      Arts     50   False
7   Sneha   Delhi  Commerce     83    True

3 Tasks using today's concepts:

Filter students from Pune, Mumbai or Nagpur using .isin()
Filter students whose name contains 'an' using .str.contains()
Filter students who are NOT from Science or Arts using ~ and .isin()

In [8]:
df[df["city"].isin(["Pune","Mumbai","Nagpur"])]

  student    city    stream  marks  passed
0   Aarav    Pune   Science     88    True
1  Ananya  Mumbai  Commerce     55    True
2  Ranjit  Nagpur      Arts     42   False
4   Karan    Pune  Commerce     67    True
5  Anjali  Mumbai   Science     78    True
6     Dev  Nagpur      Arts     50   False

In [9]:
df[df["student"].str.contains("an")]

  student    city    stream  marks  passed
1  Ananya  Mumbai  Commerce     55    True
2  Ranjit  Nagpur      Arts     42   False
4   Karan    Pune  Commerce     67    True

In [10]:
df[~df["stream"].isin(["Science" , "Arts"])]

  student    city    stream  marks  passed
1  Ananya  Mumbai  Commerce     55    True
4   Karan    Pune  Commerce     67    True
7   Sneha   Delhi  Commerce     83    True

In [11]:
data = {
    'name': ['Rahul', 'Anjali', 'Karan', 'Tanvi', 'Dev', 'Ankit', 'Priya', 'Ranjit'],
    'dept': ['HR', 'Tech', 'Finance', 'Tech', 'HR', 'Finance', 'Tech', 'HR'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Nagpur', 'Pune', 'Mumbai', 'Delhi', 'Nagpur'],
    'salary': [30000, 80000, 45000, 70000, 32000, 50000, 75000, 28000]
}
df = pd.DataFrame(data)
df

     name     dept    city  salary
0   Rahul       HR    Pune   30000
1  Anjali     Tech  Mumbai   80000
2   Karan  Finance   Delhi   45000
3   Tanvi     Tech  Nagpur   70000
4     Dev       HR    Pune   32000
5   Ankit  Finance  Mumbai   50000
6   Priya     Tech   Delhi   75000
7  Ranjit       HR  Nagpur   28000

3 Quick tasks:

Filter employees from Mumbai or Delhi using .isin()
Filter names containing 'an' using .str.contains()
Filter employees NOT in HR using ~

In [12]:
#1
df[df["city"].isin(["Mumbai","Delhi"])]

     name     dept    city  salary
1  Anjali     Tech  Mumbai   80000
2   Karan  Finance   Delhi   45000
5   Ankit  Finance  Mumbai   50000
6   Priya     Tech   Delhi   75000

In [13]:
#2
df[df["name"].str.contains("an")]

     name     dept    city  salary
2   Karan  Finance   Delhi   45000
3   Tanvi     Tech  Nagpur   70000
7  Ranjit       HR  Nagpur   28000

In [14]:
#3
df[~df["dept"].isin(["HR"])]

     name     dept    city  salary
1  Anjali     Tech  Mumbai   80000
2   Karan  Finance   Delhi   45000
3   Tanvi     Tech  Nagpur   70000
5   Ankit  Finance  Mumbai   50000
6   Priya     Tech   Delhi   75000

In [15]:
data = {
    'name': ['Amit', 'Ranya', 'Karan', 'Tanisha', 'Dev', 'Anand', 'Priya', 'Rohan'],
    'dept': ['Tech', 'HR', 'Finance', 'Tech', 'HR', 'Finance', 'Tech', 'HR'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai', 'Delhi', 'Nagpur'],
    'salary': [75000, 30000, 45000, 80000, 32000, 50000, 70000, 28000]
}
df = pd.DataFrame(data)
df

      name     dept    city  salary
0     Amit     Tech    Pune   75000
1    Ranya       HR  Mumbai   30000
2    Karan  Finance   Delhi   45000
3  Tanisha     Tech    Pune   80000
4      Dev       HR  Nagpur   32000
5    Anand  Finance  Mumbai   50000
6    Priya     Tech   Delhi   70000
7    Rohan       HR  Nagpur   28000

Filter employees from Tech or Finance using .isin()
Filter names containing 'an' using .str.contains()
Filter employees NOT from Pune or Mumbai using ~

In [16]:
#1
df[df["dept"].isin(["Tech" , "Finance"])]

      name     dept    city  salary
0     Amit     Tech    Pune   75000
2    Karan  Finance   Delhi   45000
3  Tanisha     Tech    Pune   80000
5    Anand  Finance  Mumbai   50000
6    Priya     Tech   Delhi   70000

In [17]:
#2
df[df["name"].str.contains("an")]

      name     dept    city  salary
1    Ranya       HR  Mumbai   30000
2    Karan  Finance   Delhi   45000
3  Tanisha     Tech    Pune   80000
5    Anand  Finance  Mumbai   50000
7    Rohan       HR  Nagpur   28000

In [18]:
#3
df[~df["city"].isin(["Mumbai","Pune"])]

    name     dept    city  salary
2  Karan  Finance   Delhi   45000
4    Dev       HR  Nagpur   32000
6  Priya     Tech   Delhi   70000
7  Rohan       HR  Nagpur   28000

In [19]:
data = {
    'name': ['Riya', 'Ankit', 'Karan', 'Tanvi', 'Dev', 'Anjali', 'Rohan', 'Sneha'],
    'subject': ['Math', 'Science', 'English', 'Math', 'Science', 'English', 'Math', 'Science'],
    'marks': [88, 45, 72, 91, 55, 78, 60, 83],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Nagpur', 'Pune', 'Mumbai', 'Delhi', 'Nagpur'],
    'passed': [True, False, True, True, False, True, True, True]
}
df = pd.DataFrame(data)
df

     name  subject  marks    city  passed
0    Riya     Math     88    Pune    True
1   Ankit  Science     45  Mumbai   False
2   Karan  English     72   Delhi    True
3   Tanvi     Math     91  Nagpur    True
4     Dev  Science     55    Pune   False
5  Anjali  English     78  Mumbai    True
6   Rohan     Math     60   Delhi    True
7   Sneha  Science     83  Nagpur    True

Filter passed students from Pune or Nagpur using .isin()
Filter names containing 'an' using .str.contains()
Filter students NOT in Math or Science using ~

In [20]:
df[df["city"].isin(["Pune","Nagpur"])]

    name  subject  marks    city  passed
0   Riya     Math     88    Pune    True
3  Tanvi     Math     91  Nagpur    True
4    Dev  Science     55    Pune   False
7  Sneha  Science     83  Nagpur    True

In [24]:
df[df["name"].str.contains("an")]

    name  subject  marks    city  passed
2  Karan  English     72   Delhi    True
3  Tanvi     Math     91  Nagpur    True
6  Rohan     Math     60   Delhi    True

In [25]:
df[~df["subject"].isin(["Math","Science"])]

     name  subject  marks    city  passed
2   Karan  English     72   Delhi    True
5  Anjali  English     78  Mumbai    True

In [2]:
data = {
    'name': ['Aarav', 'Anjali', 'Karan', 'Tanvi', 'Dev', 'Ankit'],
    'dept': ['Tech', 'HR', 'Finance', 'Tech', 'HR', 'Finance'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai'],
    'salary': [70000, 30000, 45000, 80000, 32000, 50000]
}
df = pd.DataFrame(data)
df

     name     dept    city  salary
0   Aarav     Tech    Pune   70000
1  Anjali       HR  Mumbai   30000
2   Karan  Finance   Delhi   45000
3   Tanvi     Tech    Pune   80000
4     Dev       HR  Nagpur   32000
5   Ankit  Finance  Mumbai   50000

Filter Tech or Finance using .isin()
Names containing 'an' using .str.contains()
NOT from Mumbai using ~

In [3]:
df[df["dept"].isin(["Tech","Finance"])]

    name     dept    city  salary
0  Aarav     Tech    Pune   70000
2  Karan  Finance   Delhi   45000
3  Tanvi     Tech    Pune   80000
5  Ankit  Finance  Mumbai   50000

In [5]:
df[df["name"].str.contains("an")]

    name     dept   city  salary
2  Karan  Finance  Delhi   45000
3  Tanvi     Tech   Pune   80000

In [6]:
df[~df["city"].isin(["Mumbai"])]

    name     dept    city  salary
0  Aarav     Tech    Pune   70000
2  Karan  Finance   Delhi   45000
3  Tanvi     Tech    Pune   80000
4    Dev       HR  Nagpur   32000