In [1]:
import pandas as pd

1. .isin() → filter multiple values cleanly
df[df['city'].isin(['Mumbai', 'Pune', 'Delhi'])]
Instead of writing 3 OR conditions!

2. .str.contains() → filter by partial text
df[df['name'].str.contains('an')]
Finds all names that contain "an" anywhere!

3. ~ (tilde) → NOT operator
df[~df['city'].isin(['Mumbai', 'Pune'])]
Gives everything EXCEPT Mumbai and Pune!

In [2]:
data = {
    'name': ['Aarav', 'Sneha', 'Ranjeet', 'Priya', 'Karan', 'Ankit', 'Divya', 'Rohan'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai', 'Delhi', 'Nagpur'],
    'department': ['HR', 'Tech', 'Finance', 'Tech', 'HR', 'Finance', 'Tech', 'HR'],
    'salary': [30000, 75000, 45000, 68000, 32000, 50000, 80000, 28000]
}
df = pd.DataFrame(data)
df

      name    city department  salary
0    Aarav    Pune         HR   30000
1    Sneha  Mumbai       Tech   75000
2  Ranjeet   Delhi    Finance   45000
3    Priya    Pune       Tech   68000
4    Karan  Nagpur         HR   32000
5    Ankit  Mumbai    Finance   50000
6    Divya   Delhi       Tech   80000
7    Rohan  Nagpur         HR   28000

3 Tasks:
Filter employees from Pune, Mumbai or Nagpur using .isin()
Filter employees whose name contains 'an' using .str.contains()
Filter employees who are NOT in Tech or Finance using ~ and .isin()

In [5]:
df[df["city"].isin(["Mumbai" , "Pune" , "Nagpur"])]

    name    city department  salary
0  Aarav    Pune         HR   30000
1  Sneha  Mumbai       Tech   75000
3  Priya    Pune       Tech   68000
4  Karan  Nagpur         HR   32000
5  Ankit  Mumbai    Finance   50000
7  Rohan  Nagpur         HR   28000

In [6]:
df[df["name"].str.contains("an")]

      name    city department  salary
2  Ranjeet   Delhi    Finance   45000
4    Karan  Nagpur         HR   32000
7    Rohan  Nagpur         HR   28000

In [7]:
df[~df["department"].isin(["Tech","Finance"])]

    name    city department  salary
0  Aarav    Pune         HR   30000
4  Karan  Nagpur         HR   32000
7  Rohan  Nagpur         HR   28000