In [1]:
import pandas as pd

data = {
    'name': ['Aarav', 'Sneha', 'Rahul', 'Priya', 'Karan', 'Mehta', 'Divya', 'Rohan'],
    'age': [22, 25, 19, 30, 21, 28, 24, 35],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Pune', 'Mumbai'],
    'salary': [25000, 45000, 20000, 60000, 22000, 50000, 35000, 70000],
    'experience': [1, 3, 0, 6, 1, 4, 2, 8]
}

df = pd.DataFrame(data)
df

    name  age    city  salary  experience
0  Aarav   22    Pune   25000           1
1  Sneha   25  Mumbai   45000           3
2  Rahul   19   Delhi   20000           0
3  Priya   30    Pune   60000           6
4  Karan   21  Mumbai   22000           1
5  Mehta   28   Delhi   50000           4
6  Divya   24    Pune   35000           2
7  Rohan   35  Mumbai   70000           8

3 Filtering Tasks:

Filter all employees from Pune with salary greater than 30000
Filter employees whose age is between 20 and 26 (inclusive)
Filter employees with experience greater than 2 and city is not Delhi

In [2]:
#1 
df[(df["city"] == "Pune") & (df["salary"] > 30000)]

    name  age  city  salary  experience
3  Priya   30  Pune   60000           6
6  Divya   24  Pune   35000           2

In [3]:
#2
df[df[ 20 <= ["age"] <= 26]]

TypeError: '<=' not supported between instances of 'int' and 'list'

In [ ]:
#3
df[(df["experience"] > 2) & (df["city"] != "Delhi")]

In [ ]:
# Option A — using &
df[(df["age"] >= 20) & (df["age"] <= 26)]

In [ ]:
# Option B — using .between():
df[df["age"].between(20, 26)]

## **Practice Data NO.2**

In [4]:
import pandas as pd

data = {
    'student': ['Riya', 'Arjun', 'Sneha', 'Dev', 'Pooja', 'Karan', 'Meera', 'Sahil'],
    'marks': [85, 42, 91, 55, 78, 33, 88, 60],
    'grade': ['A', 'D', 'A', 'C', 'B', 'F', 'A', 'C'],
    'subject': ['Math', 'Science', 'Math', 'English', 'Science', 'Math', 'English', 'Science'],
    'attendance': [95, 60, 98, 72, 85, 45, 92, 78]
}

df = pd.DataFrame(data)
df

  student  marks grade  subject  attendance
0    Riya     85     A     Math          95
1   Arjun     42     D  Science          60
2   Sneha     91     A     Math          98
3     Dev     55     C  English          72
4   Pooja     78     B  Science          85
5   Karan     33     F     Math          45
6   Meera     88     A  English          92
7   Sahil     60     C  Science          78

3 Filtering Tasks:

Filter students who have grade A or B
Filter students with attendance less than 75 and marks less than 60
Filter students who study Math or Science and have marks greater than 50

In [7]:
#1
df[(df["grade"] == "A") | (df["grade"] == "B")]

  student  marks grade  subject  attendance
0    Riya     85     A     Math          95
2   Sneha     91     A     Math          98
4   Pooja     78     B  Science          85
6   Meera     88     A  English          92

In [9]:
#2
df[(df["attendance"] < 75 ) & (df["marks"] < 60)]

  student  marks grade  subject  attendance
1   Arjun     42     D  Science          60
3     Dev     55     C  English          72
5   Karan     33     F     Math          45

In [15]:
#3
df[((df["subject"] == "Math") | (df["subject"] == "Science")) & (df["marks"] > 50)]

  student  marks grade  subject  attendance
0    Riya     85     A     Math          95
2   Sneha     91     A     Math          98
4   Pooja     78     B  Science          85
7   Sahil     60     C  Science          78

The catch in the 3rd filtering was always cover the or statement in extra bracket when combining with and

### **Practice data no. 3**

In [6]:
import pandas as pd

data = {
    'product': ['Laptop', 'Phone', 'Tablet', 'Watch', 'Earbuds', 'Monitor', 'Keyboard', 'Mouse'],
    'brand': ['Dell', 'Samsung', 'Apple', 'Apple', 'Sony', 'LG', 'Dell', 'Logitech'],
    'price': [75000, 25000, 60000, 35000, 8000, 20000, 3000, 1500],
    'rating': [4.5, 4.2, 4.8, 3.9, 4.1, 4.3, 3.7, 4.6],
    'stock': [10, 0, 5, 8, 0, 3, 15, 20]
}

df = pd.DataFrame(data)
df

    product     brand  price  rating  stock
0    Laptop      Dell  75000     4.5     10
1     Phone   Samsung  25000     4.2      0
2    Tablet     Apple  60000     4.8      5
3     Watch     Apple  35000     3.9      8
4   Earbuds      Sony   8000     4.1      0
5   Monitor        LG  20000     4.3      3
6  Keyboard      Dell   3000     3.7     15
7     Mouse  Logitech   1500     4.6     20

3 Filtering Tasks:

Filter products that are in stock (stock > 0) and have rating above 4.2
Filter products from Apple or Sony with price greater than 20000
Filter products where brand is not Dell and price is between 5000 and 40000

In [7]:
#1
df[(df["stock"] > 0) & (df["rating"] > 4.2)]

   product     brand  price  rating  stock
0   Laptop      Dell  75000     4.5     10
2   Tablet     Apple  60000     4.8      5
5  Monitor        LG  20000     4.3      3
7    Mouse  Logitech   1500     4.6     20

In [8]:
#2
df[((df["brand"] == "Apple") | (df["brand"] == "Sony")) & (df["price"] > 20000)]

  product  brand  price  rating  stock
2  Tablet  Apple  60000     4.8      5
3   Watch  Apple  35000     3.9      8

In [9]:
#3
df[(df["brand"] != "Dell") & (df["price"].between(5000 , 40000))]

   product    brand  price  rating  stock
1    Phone  Samsung  25000     4.2      0
3    Watch    Apple  35000     3.9      8
4  Earbuds     Sony   8000     4.1      0
5  Monitor       LG  20000     4.3      3

3 Trickier Tasks:

Filter products that are out of stock OR have rating below 4.0
Filter products where brand is neither Apple nor LG and price is less than 30000
Filter products where price is above 10000 and rating is between 4.0 and 4.5 and stock is greater than 0

In [10]:
#1
df[(df["stock"] ==0 ) | (df["rating"] < 4.0)]

    product    brand  price  rating  stock
1     Phone  Samsung  25000     4.2      0
3     Watch    Apple  35000     3.9      8
4   Earbuds     Sony   8000     4.1      0
6  Keyboard     Dell   3000     3.7     15

In [12]:
#2
df[((df["brand"] != "Apple") & (df["brand"] != "LG")) & (df["price"] < 30000)]

    product     brand  price  rating  stock
1     Phone   Samsung  25000     4.2      0
4   Earbuds      Sony   8000     4.1      0
6  Keyboard      Dell   3000     3.7     15
7     Mouse  Logitech   1500     4.6     20

In [18]:
#3
df[((df["rating"].between(4.0 , 4.5))) & ((df["price"] > 10000)) & ((df["stock"] > 0))]

   product brand  price  rating  stock
0   Laptop  Dell  75000     4.5     10
5  Monitor    LG  20000     4.3      3

### **Practice data number 4!**

In [22]:
data = {
    'employee': ['Amit', 'Sara', 'Raj', 'Nisha', 'Vikram', 'Priya', 'Karan', 'Deepa'],
    'department': ['HR', 'Tech', 'Tech', 'Finance', 'HR', 'Tech', 'Finance', 'HR'],
    'salary': [30000, 75000, 68000, 45000, 32000, 80000, 50000, 28000],
    'experience': [2, 5, 4, 3, 1, 6, 4, 1],
    'performance': [3.5, 4.8, 4.2, 3.8, 3.1, 4.9, 4.0, 3.3]
}
df = pd.DataFrame(data)
df

  employee department  salary  experience  performance
0     Amit         HR   30000           2          3.5
1     Sara       Tech   75000           5          4.8
2      Raj       Tech   68000           4          4.2
3    Nisha    Finance   45000           3          3.8
4   Vikram         HR   32000           1          3.1
5    Priya       Tech   80000           6          4.9
6    Karan    Finance   50000           4          4.0
7    Deepa         HR   28000           1          3.3

Filter Tech employees with salary above 70000
Filter employees with experience less than 3 or performance below 3.5
Filter employees from HR or Finance with performance between 3.5 and 4.0 and salary less than 40000

In [24]:
#1
df[(df["salary"] > 70000)]

  employee department  salary  experience  performance
1     Sara       Tech   75000           5          4.8
5    Priya       Tech   80000           6          4.9

In [35]:
#2
df[(df["experience"] < 3 ) | (df["performance"] < 3.5)]

  employee department  salary  experience  performance
0     Amit         HR   30000           2          3.5
4   Vikram         HR   32000           1          3.1
7    Deepa         HR   28000           1          3.3

In [38]:
#3
df[((df["department"] == "HR") | (df["department"] == "Finance")) & (df["performance"].between(3.5,4.0)) & (df["salary"] < 40000)]

  employee department  salary  experience  performance
0     Amit         HR   30000           2          3.5