In [3]:
import pandas as pd

In [4]:
data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [25, 30, 35, 40, 28],
    "City": ["Mumbai", "Pune", "Mumbai", "Delhi", "Pune"],
    "Salary": [50000, 60000, 70000, 80000, 65000]
}

In [6]:
df = pd.DataFrame(data)
df

  Name  Age    City  Salary
0    A   25  Mumbai   50000
1    B   30    Pune   60000
2    C   35  Mumbai   70000
3    D   40   Delhi   80000
4    E   28    Pune   65000

1️⃣ Basic check
Show first 3 rows
Show dataset info
Show summary stats

In [7]:
df.head(3)

  Name  Age    City  Salary
0    A   25  Mumbai   50000
1    B   30    Pune   60000
2    C   35  Mumbai   70000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
 3   Salary  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 322.0 bytes

In [9]:
df.describe()

            Age        Salary
count   5.00000      5.000000
mean   31.60000  65000.000000
std     5.94138  11180.339887
min    25.00000  50000.000000
25%    28.00000  60000.000000
50%    30.00000  65000.000000
75%    35.00000  70000.000000
max    40.00000  80000.000000

2️⃣ Filtering (important)
Get people from Mumbai
Get people with Salary > 60000
Get people from Pune AND Age < 30

In [13]:
df[(df["City"] == "Mumbai")]

  Name  Age    City  Salary
0    A   25  Mumbai   50000
2    C   35  Mumbai   70000

In [14]:
df[df["Salary"] > 60000]

  Name  Age    City  Salary
2    C   35  Mumbai   70000
3    D   40   Delhi   80000
4    E   28    Pune   65000

In [24]:
df[(df["City"] == "Pune") & (df["Age"] < 30)]

  Name  Age  City  Salary
4    E   28  Pune   65000

3️⃣ Column operations
Create new column:
Bonus = Salary * 0.10
Create another:
Age_after_5 = Age + 5

In [26]:
df["Bonus"] = df["Salary"] * 0.10
df

  Name  Age    City  Salary   Bonus
0    A   25  Mumbai   50000  5000.0
1    B   30    Pune   60000  6000.0
2    C   35  Mumbai   70000  7000.0
3    D   40   Delhi   80000  8000.0
4    E   28    Pune   65000  6500.0

In [27]:
df["Age_after_5"] = df["Age"] + 5
df

  Name  Age    City  Salary   Bonus  Age_after_5
0    A   25  Mumbai   50000  5000.0           30
1    B   30    Pune   60000  6000.0           35
2    C   35  Mumbai   70000  7000.0           40
3    D   40   Delhi   80000  8000.0           45
4    E   28    Pune   65000  6500.0           33

Understand this deeply:

Think like this:

df["NewColumn"] = something

Left side → new column name

Right side → calculation using existing columns

4️⃣ .loc practice (VERY IMPORTANT)
Get rows where Salary > 60000, only show Name and Salary
Change Salary of person “A” to 55000 using .loc

In [28]:
df.loc["Name" , "Salary" > 60000]

TypeError: '>' not supported between instances of 'str' and 'int'

5️⃣ GroupBy (core concept)
Find average salary per city

In [29]:
df.groupby("City")["Salary"].mean()

City
Delhi     80000.0
Mumbai    60000.0
Pune      62500.0
Name: Salary, dtype: float64

6️⃣ Sorting
Sort by Salary descending

In [31]:
df.sort_values("Salary" , ascending = False)

  Name  Age    City  Salary   Bonus  Age_after_5
3    D   40   Delhi   80000  8000.0           45
2    C   35  Mumbai   70000  7000.0           40
4    E   28    Pune   65000  6500.0           33
1    B   30    Pune   60000  6000.0           35
0    A   25  Mumbai   50000  5000.0           30

7️⃣ Value counts
Count how many people in each city

In [34]:
df["City"].value_counts()

City
Mumbai    2
Pune      2
Delhi     1
Name: count, dtype: int64