In [1]:
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan"],
    "Maths": [85, 92, 78, 88, 95],
    "Science": [90, 85, 80, 91, 89],
    "English": [78, 88, 84, 90, 87]
}

df = pd.DataFrame(data)
df

    Name  Maths  Science  English
0   Amit     85       90       78
1  Priya     92       85       88
2  Rahul     78       80       84
3  Sneha     88       91       90
4  Karan     95       89       87

Tasks
Display the first 3 rows.
Calculate the average marks in Maths.
Add a new column called Total.
Add a new column called Percentage.
Find the student with the highest Total marks.
Display only students whose Percentage is greater than 85%.
Sort the DataFrame by Percentage in descending order.

In [2]:
#1
df.head(3)

    Name  Maths  Science  English
0   Amit     85       90       78
1  Priya     92       85       88
2  Rahul     78       80       84

In [3]:
#2
print("average_marks_of_maths",df["Maths"].mean())

average_marks_of_maths 87.6

In [4]:
#3
df["Total"] = df["Maths"] + df["Science"] + df["English"]
df

    Name  Maths  Science  English  Total
0   Amit     85       90       78    253
1  Priya     92       85       88    265
2  Rahul     78       80       84    242
3  Sneha     88       91       90    269
4  Karan     95       89       87    271

In [5]:
#4
df["Percentage"] = df["Total"] / 3
df

    Name  Maths  Science  English  Total  Percentage
0   Amit     85       90       78    253   84.333333
1  Priya     92       85       88    265   88.333333
2  Rahul     78       80       84    242   80.666667
3  Sneha     88       91       90    269   89.666667
4  Karan     95       89       87    271   90.333333

In [6]:
#5
df[df["Percentage"] > 85]

    Name  Maths  Science  English  Total  Percentage
1  Priya     92       85       88    265   88.333333
3  Sneha     88       91       90    269   89.666667
4  Karan     95       89       87    271   90.333333

In [7]:
#6
df.loc[df["Total"].idxmax()]

Name              Karan
Maths                95
Science              89
English              87
Total               271
Percentage    90.333333
Name: 4, dtype: object

In [8]:
df.sort_values(by="Percentage", ascending=False)

    Name  Maths  Science  English  Total  Percentage
4  Karan     95       89       87    271   90.333333
3  Sneha     88       91       90    269   89.666667
1  Priya     92       85       88    265   88.333333
0   Amit     85       90       78    253   84.333333
2  Rahul     78       80       84    242   80.666667

In [9]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Marks": [70, 85, 90]
})
df = pd.DataFrame(df)
df

  Name  Marks
0    A     70
1    B     85
2    C     90

Tasks
Create a new column called Bonus with value 5 for every student.
Create a new column called Final_Marks = Marks + Bonus.
Print the DataFrame.

In [10]:
#1
df["Bonus"] = 5
df

  Name  Marks  Bonus
0    A     70      5
1    B     85      5
2    C     90      5

In [11]:
#2
df["Final Marks"] = df["Marks"] + df["Bonus"]
df

  Name  Marks  Bonus  Final Marks
0    A     70      5           75
1    B     85      5           90
2    C     90      5           95

In [12]:
#3
df

  Name  Marks  Bonus  Final Marks
0    A     70      5           75
1    B     85      5           90
2    C     90      5           95

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Price": [100, 200, 300]
})
df = pd.DataFrame(df)
df

   Price
0    100
1    200
2    300

In [16]:
df["GST"] = df["Price"] * 0.18
df

   Price   GST
0    100  18.0
1    200  36.0
2    300  54.0