In [2]:
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan"],
    "Maths": [85, 92, 78, 88, 95],
    "Science": [90, 85, 80, 91, 89],
    "English": [78, 88, 84, 90, 87]
}

df = pd.DataFrame(data)
df

    Name  Maths  Science  English
0   Amit     85       90       78
1  Priya     92       85       88
2  Rahul     78       80       84
3  Sneha     88       91       90
4  Karan     95       89       87

Tasks
Display the first 3 rows.
Calculate the average marks in Maths.
Add a new column called Total.
Add a new column called Percentage.
Find the student with the highest Total marks.
Display only students whose Percentage is greater than 85%.
Sort the DataFrame by Percentage in descending order.

In [9]:
#1
df.head(3)

    Name  Maths  Science  English
0   Amit     85       90       78
1  Priya     92       85       88
2  Rahul     78       80       84

In [10]:
#2
print("average_marks_of_maths",df["Maths"].mean())

average_marks_of_maths 87.6

In [13]:
#3
df["Total"] = df["Maths"] + df["Science"] + df["English"]
df

    Name  Maths  Science  English  Total
0   Amit     85       90       78    253
1  Priya     92       85       88    265
2  Rahul     78       80       84    242
3  Sneha     88       91       90    269
4  Karan     95       89       87    271

In [14]:
#4
df["Percentage"] = df["Total"] / 3
df

    Name  Maths  Science  English  Total  Percentage
0   Amit     85       90       78    253   84.333333
1  Priya     92       85       88    265   88.333333
2  Rahul     78       80       84    242   80.666667
3  Sneha     88       91       90    269   89.666667
4  Karan     95       89       87    271   90.333333

In [15]:
#5
df[df["Percentage"] > 85]

    Name  Maths  Science  English  Total  Percentage
1  Priya     92       85       88    265   88.333333
3  Sneha     88       91       90    269   89.666667
4  Karan     95       89       87    271   90.333333

In [21]:
#6
df.loc[df["Total"].idxmax()]

Name              Karan
Maths                95
Science              89
English              87
Total               271
Percentage    90.333333
Name: 4, dtype: object

In [22]:
df.sort_values(by="Percentage", ascending=False)

    Name  Maths  Science  English  Total  Percentage
4  Karan     95       89       87    271   90.333333
3  Sneha     88       91       90    269   89.666667
1  Priya     92       85       88    265   88.333333
0   Amit     85       90       78    253   84.333333
2  Rahul     78       80       84    242   80.666667