In [1]:
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan"],
    "Maths": [85, 92, 78, 88, 95],
    "Science": [90, 85, 80, 91, 89],
    "English": [78, 88, 84, 90, 87]
}

df = pd.DataFrame(data)
df

    Name  Maths  Science  English
0   Amit     85       90       78
1  Priya     92       85       88
2  Rahul     78       80       84
3  Sneha     88       91       90
4  Karan     95       89       87

Tasks
Display the first 3 rows.
Calculate the average marks in Maths.
Add a new column called Total.
Add a new column called Percentage.
Find the student with the highest Total marks.
Display only students whose Percentage is greater than 85%.
Sort the DataFrame by Percentage in descending order.

In [2]:
#1
df.head(3)

    Name  Maths  Science  English
0   Amit     85       90       78
1  Priya     92       85       88
2  Rahul     78       80       84

In [3]:
#2
print("average_marks_of_maths",df["Maths"].mean())

average_marks_of_maths 87.6

In [4]:
#3
df["Total"] = df["Maths"] + df["Science"] + df["English"]
df

    Name  Maths  Science  English  Total
0   Amit     85       90       78    253
1  Priya     92       85       88    265
2  Rahul     78       80       84    242
3  Sneha     88       91       90    269
4  Karan     95       89       87    271

In [5]:
#4
df["Percentage"] = df["Total"] / 3
df

    Name  Maths  Science  English  Total  Percentage
0   Amit     85       90       78    253   84.333333
1  Priya     92       85       88    265   88.333333
2  Rahul     78       80       84    242   80.666667
3  Sneha     88       91       90    269   89.666667
4  Karan     95       89       87    271   90.333333

In [6]:
#5
df[df["Percentage"] > 85]

    Name  Maths  Science  English  Total  Percentage
1  Priya     92       85       88    265   88.333333
3  Sneha     88       91       90    269   89.666667
4  Karan     95       89       87    271   90.333333

In [7]:
#6
df.loc[df["Total"].idxmax()]

Name              Karan
Maths                95
Science              89
English              87
Total               271
Percentage    90.333333
Name: 4, dtype: object

In [8]:
df.sort_values(by="Percentage", ascending=False)

    Name  Maths  Science  English  Total  Percentage
4  Karan     95       89       87    271   90.333333
3  Sneha     88       91       90    269   89.666667
1  Priya     92       85       88    265   88.333333
0   Amit     85       90       78    253   84.333333
2  Rahul     78       80       84    242   80.666667

In [9]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Marks": [70, 85, 90]
})
df = pd.DataFrame(df)
df

  Name  Marks
0    A     70
1    B     85
2    C     90

Tasks
Create a new column called Bonus with value 5 for every student.
Create a new column called Final_Marks = Marks + Bonus.
Print the DataFrame.

In [10]:
#1
df["Bonus"] = 5
df

  Name  Marks  Bonus
0    A     70      5
1    B     85      5
2    C     90      5

In [11]:
#2
df["Final Marks"] = df["Marks"] + df["Bonus"]
df

  Name  Marks  Bonus  Final Marks
0    A     70      5           75
1    B     85      5           90
2    C     90      5           95

In [12]:
#3
df

  Name  Marks  Bonus  Final Marks
0    A     70      5           75
1    B     85      5           90
2    C     90      5           95

In [13]:
import pandas as pd

df = pd.DataFrame({
    "Price": [100, 200, 300]
})
df = pd.DataFrame(df)
df

   Price
0    100
1    200
2    300

In [14]:
df["GST"] = df["Price"] * 0.18
df

   Price   GST
0    100  18.0
1    200  36.0
2    300  54.0

In [15]:
data = {
    'name': ['Riya', 'Anand', 'Karan', 'Tanvi', 'Dev', 'Anjali', 'Rohan', 'Sneha'],
    'category': ['Food', 'Electronics', 'Clothing', 'Food', 'Electronics', 'Clothing', 'Food', 'Electronics'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Nagpur', 'Pune', 'Mumbai', 'Delhi', 'Nagpur'],
    'amount': [500, 15000, 2000, 800, 12000, 3000, 600, 18000],
    'delivered': [True, False, True, True, False, True, True, False]
}
df = pd.DataFrame(data)
df

     name     category    city  amount  delivered
0    Riya         Food    Pune     500       True
1   Anand  Electronics  Mumbai   15000      False
2   Karan     Clothing   Delhi    2000       True
3   Tanvi         Food  Nagpur     800       True
4     Dev  Electronics    Pune   12000      False
5  Anjali     Clothing  Mumbai    3000       True
6   Rohan         Food   Delhi     600       True
7   Sneha  Electronics  Nagpur   18000      False

Filter Food or Clothing orders using .isin()
Filter names containing 'an' using .str.contains()
Filter delivered orders NOT from Pune or Delhi using ~ and isin()

In [16]:
#1
df[df["category"].isin(["Food" , "Clothing"])]

     name  category    city  amount  delivered
0    Riya      Food    Pune     500       True
2   Karan  Clothing   Delhi    2000       True
3   Tanvi      Food  Nagpur     800       True
5  Anjali  Clothing  Mumbai    3000       True
6   Rohan      Food   Delhi     600       True

In [17]:
#2
df[df["name"].str.contains("an")]

    name     category    city  amount  delivered
1  Anand  Electronics  Mumbai   15000      False
2  Karan     Clothing   Delhi    2000       True
3  Tanvi         Food  Nagpur     800       True
6  Rohan         Food   Delhi     600       True

In [18]:
#3
df[(df["delivered"] == True) & (~df["city"].isin(["Pune","Delhi"]))]

     name  category    city  amount  delivered
3   Tanvi      Food  Nagpur     800       True
5  Anjali  Clothing  Mumbai    3000       True

In [19]:
data = {
    'movie': ['Inception', 'Titanic', 'Avatar', 'Joker', 'Frozen', 'Up', 'Coco', 'Tenet'],
    'genre': ['Sci-Fi', 'Romance', 'Sci-Fi', 'Drama', 'Animation', 'Animation', 'Animation', 'Sci-Fi'],
    'year': [2010, 1997, 2009, 2019, 2013, 2009, 2017, 2020],
    'rating': [8.8, 7.8, 7.8, 8.4, 7.4, 8.2, 8.4, 7.3],
    'budget_million': [160, 200, 237, 55, 150, 175, 175, 205]
}
df = pd.DataFrame(data)
df

       movie      genre  year  rating  budget_million
0  Inception     Sci-Fi  2010     8.8             160
1    Titanic    Romance  1997     7.8             200
2     Avatar     Sci-Fi  2009     7.8             237
3      Joker      Drama  2019     8.4              55
4     Frozen  Animation  2013     7.4             150
5         Up  Animation  2009     8.2             175
6       Coco  Animation  2017     8.4             175
7      Tenet     Sci-Fi  2020     7.3             205

Filter movies with rating above 8.0 using simple condition
Which genre has the most movies? (.value_counts())
Filter movies that are Sci-Fi or Animation using .isin()

In [20]:
df[(df["rating"] > 8.0)]

       movie      genre  year  rating  budget_million
0  Inception     Sci-Fi  2010     8.8             160
3      Joker      Drama  2019     8.4              55
5         Up  Animation  2009     8.2             175
6       Coco  Animation  2017     8.4             175

In [21]:
df["genre"].value_counts().head(1)

genre
Sci-Fi    3
Name: count, dtype: int64

In [22]:
df[df["genre"].isin(["Sci-Fi" , "Animation"])]

       movie      genre  year  rating  budget_million
0  Inception     Sci-Fi  2010     8.8             160
2     Avatar     Sci-Fi  2009     7.8             237
4     Frozen  Animation  2013     7.4             150
5         Up  Animation  2009     8.2             175
6       Coco  Animation  2017     8.4             175
7      Tenet     Sci-Fi  2020     7.3             205

In [23]:
data = {
    'name': ['Riya', 'Anand', 'Karan', 'Tanvi', 'Dev', 'Anjali', 'Rohan', 'Sneha'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai', 'Delhi', 'Nagpur'],
    'score': [88, 45, 72, 91, 55, 78, 60, 83],
    'passed': [True, False, True, True, False, True, True, True]
}
df = pd.DataFrame(data)
df

     name    city  score  passed
0    Riya    Pune     88    True
1   Anand  Mumbai     45   False
2   Karan   Delhi     72    True
3   Tanvi    Pune     91    True
4     Dev  Nagpur     55   False
5  Anjali  Mumbai     78    True
6   Rohan   Delhi     60    True
7   Sneha  Nagpur     83    True

3 tasks:

Filter passed students with score above 80
Which city has most students?
Filter students NOT from Pune or Delhi

In [24]:
#1
df[(df["passed"] == True) & (df["score"] > 80)]

    name    city  score  passed
0   Riya    Pune     88    True
3  Tanvi    Pune     91    True
7  Sneha  Nagpur     83    True

In [27]:
#2
df.loc[df["name"].idxmax(),"city"]

'Pune'

In [28]:
#3
df[~df["city"].isin(["Pune","Delhi"])]

     name    city  score  passed
1   Anand  Mumbai     45   False
4     Dev  Nagpur     55   False
5  Anjali  Mumbai     78    True
7   Sneha  Nagpur     83    True