In [1]:
import pandas as pd

data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan"],
    "Maths": [85, 92, 78, 88, 95],
    "Science": [90, 85, 80, 91, 89],
    "English": [78, 88, 84, 90, 87]
}

df = pd.DataFrame(data)
df

    Name  Maths  Science  English
0   Amit     85       90       78
1  Priya     92       85       88
2  Rahul     78       80       84
3  Sneha     88       91       90
4  Karan     95       89       87

Tasks
Display the first 3 rows.
Calculate the average marks in Maths.
Add a new column called Total.
Add a new column called Percentage.
Find the student with the highest Total marks.
Display only students whose Percentage is greater than 85%.
Sort the DataFrame by Percentage in descending order.

In [2]:
#1
df.head(3)

    Name  Maths  Science  English
0   Amit     85       90       78
1  Priya     92       85       88
2  Rahul     78       80       84

In [3]:
#2
print("average_marks_of_maths",df["Maths"].mean())

average_marks_of_maths 87.6

In [4]:
#3
df["Total"] = df["Maths"] + df["Science"] + df["English"]
df

    Name  Maths  Science  English  Total
0   Amit     85       90       78    253
1  Priya     92       85       88    265
2  Rahul     78       80       84    242
3  Sneha     88       91       90    269
4  Karan     95       89       87    271

In [5]:
#4
df["Percentage"] = df["Total"] / 3
df

    Name  Maths  Science  English  Total  Percentage
0   Amit     85       90       78    253   84.333333
1  Priya     92       85       88    265   88.333333
2  Rahul     78       80       84    242   80.666667
3  Sneha     88       91       90    269   89.666667
4  Karan     95       89       87    271   90.333333

In [6]:
#5
df[df["Percentage"] > 85]

    Name  Maths  Science  English  Total  Percentage
1  Priya     92       85       88    265   88.333333
3  Sneha     88       91       90    269   89.666667
4  Karan     95       89       87    271   90.333333

In [7]:
#6
df.loc[df["Total"].idxmax()]

Name              Karan
Maths                95
Science              89
English              87
Total               271
Percentage    90.333333
Name: 4, dtype: object

In [8]:
df.sort_values(by="Percentage", ascending=False)

    Name  Maths  Science  English  Total  Percentage
4  Karan     95       89       87    271   90.333333
3  Sneha     88       91       90    269   89.666667
1  Priya     92       85       88    265   88.333333
0   Amit     85       90       78    253   84.333333
2  Rahul     78       80       84    242   80.666667

In [9]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Marks": [70, 85, 90]
})
df = pd.DataFrame(df)
df

  Name  Marks
0    A     70
1    B     85
2    C     90

Tasks
Create a new column called Bonus with value 5 for every student.
Create a new column called Final_Marks = Marks + Bonus.
Print the DataFrame.

In [10]:
#1
df["Bonus"] = 5
df

  Name  Marks  Bonus
0    A     70      5
1    B     85      5
2    C     90      5

In [11]:
#2
df["Final Marks"] = df["Marks"] + df["Bonus"]
df

  Name  Marks  Bonus  Final Marks
0    A     70      5           75
1    B     85      5           90
2    C     90      5           95

In [12]:
#3
df

  Name  Marks  Bonus  Final Marks
0    A     70      5           75
1    B     85      5           90
2    C     90      5           95

In [13]:
import pandas as pd

df = pd.DataFrame({
    "Price": [100, 200, 300]
})
df = pd.DataFrame(df)
df

   Price
0    100
1    200
2    300

In [14]:
df["GST"] = df["Price"] * 0.18
df

   Price   GST
0    100  18.0
1    200  36.0
2    300  54.0

In [15]:
data = {
    'name': ['Riya', 'Anand', 'Karan', 'Tanvi', 'Dev', 'Anjali', 'Rohan', 'Sneha'],
    'category': ['Food', 'Electronics', 'Clothing', 'Food', 'Electronics', 'Clothing', 'Food', 'Electronics'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Nagpur', 'Pune', 'Mumbai', 'Delhi', 'Nagpur'],
    'amount': [500, 15000, 2000, 800, 12000, 3000, 600, 18000],
    'delivered': [True, False, True, True, False, True, True, False]
}
df = pd.DataFrame(data)
df

     name     category    city  amount  delivered
0    Riya         Food    Pune     500       True
1   Anand  Electronics  Mumbai   15000      False
2   Karan     Clothing   Delhi    2000       True
3   Tanvi         Food  Nagpur     800       True
4     Dev  Electronics    Pune   12000      False
5  Anjali     Clothing  Mumbai    3000       True
6   Rohan         Food   Delhi     600       True
7   Sneha  Electronics  Nagpur   18000      False

Filter Food or Clothing orders using .isin()
Filter names containing 'an' using .str.contains()
Filter delivered orders NOT from Pune or Delhi using ~ and isin()

In [16]:
#1
df[df["category"].isin(["Food" , "Clothing"])]

     name  category    city  amount  delivered
0    Riya      Food    Pune     500       True
2   Karan  Clothing   Delhi    2000       True
3   Tanvi      Food  Nagpur     800       True
5  Anjali  Clothing  Mumbai    3000       True
6   Rohan      Food   Delhi     600       True

In [17]:
#2
df[df["name"].str.contains("an")]

    name     category    city  amount  delivered
1  Anand  Electronics  Mumbai   15000      False
2  Karan     Clothing   Delhi    2000       True
3  Tanvi         Food  Nagpur     800       True
6  Rohan         Food   Delhi     600       True

In [18]:
#3
df[(df["delivered"] == True) & (~df["city"].isin(["Pune","Delhi"]))]

     name  category    city  amount  delivered
3   Tanvi      Food  Nagpur     800       True
5  Anjali  Clothing  Mumbai    3000       True

In [19]:
data = {
    'movie': ['Inception', 'Titanic', 'Avatar', 'Joker', 'Frozen', 'Up', 'Coco', 'Tenet'],
    'genre': ['Sci-Fi', 'Romance', 'Sci-Fi', 'Drama', 'Animation', 'Animation', 'Animation', 'Sci-Fi'],
    'year': [2010, 1997, 2009, 2019, 2013, 2009, 2017, 2020],
    'rating': [8.8, 7.8, 7.8, 8.4, 7.4, 8.2, 8.4, 7.3],
    'budget_million': [160, 200, 237, 55, 150, 175, 175, 205]
}
df = pd.DataFrame(data)
df

       movie      genre  year  rating  budget_million
0  Inception     Sci-Fi  2010     8.8             160
1    Titanic    Romance  1997     7.8             200
2     Avatar     Sci-Fi  2009     7.8             237
3      Joker      Drama  2019     8.4              55
4     Frozen  Animation  2013     7.4             150
5         Up  Animation  2009     8.2             175
6       Coco  Animation  2017     8.4             175
7      Tenet     Sci-Fi  2020     7.3             205

Filter movies with rating above 8.0 using simple condition
Which genre has the most movies? (.value_counts())
Filter movies that are Sci-Fi or Animation using .isin()

In [20]:
df[(df["rating"] > 8.0)]

       movie      genre  year  rating  budget_million
0  Inception     Sci-Fi  2010     8.8             160
3      Joker      Drama  2019     8.4              55
5         Up  Animation  2009     8.2             175
6       Coco  Animation  2017     8.4             175

In [21]:
df["genre"].value_counts().head(1)

genre
Sci-Fi    3
Name: count, dtype: int64

In [22]:
df[df["genre"].isin(["Sci-Fi" , "Animation"])]

       movie      genre  year  rating  budget_million
0  Inception     Sci-Fi  2010     8.8             160
2     Avatar     Sci-Fi  2009     7.8             237
4     Frozen  Animation  2013     7.4             150
5         Up  Animation  2009     8.2             175
6       Coco  Animation  2017     8.4             175
7      Tenet     Sci-Fi  2020     7.3             205

In [23]:
data = {
    'name': ['Riya', 'Anand', 'Karan', 'Tanvi', 'Dev', 'Anjali', 'Rohan', 'Sneha'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai', 'Delhi', 'Nagpur'],
    'score': [88, 45, 72, 91, 55, 78, 60, 83],
    'passed': [True, False, True, True, False, True, True, True]
}
df = pd.DataFrame(data)
df

     name    city  score  passed
0    Riya    Pune     88    True
1   Anand  Mumbai     45   False
2   Karan   Delhi     72    True
3   Tanvi    Pune     91    True
4     Dev  Nagpur     55   False
5  Anjali  Mumbai     78    True
6   Rohan   Delhi     60    True
7   Sneha  Nagpur     83    True

3 tasks:

Filter passed students with score above 80
Which city has most students?
Filter students NOT from Pune or Delhi

In [24]:
#1
df[(df["passed"] == True) & (df["score"] > 80)]

    name    city  score  passed
0   Riya    Pune     88    True
3  Tanvi    Pune     91    True
7  Sneha  Nagpur     83    True

In [25]:
#2
df.loc[df["name"].idxmax(),"city"]

'Pune'

In [26]:
#3
df[~df["city"].isin(["Pune","Delhi"])]

     name    city  score  passed
1   Anand  Mumbai     45   False
4     Dev  Nagpur     55   False
5  Anjali  Mumbai     78    True
7   Sneha  Nagpur     83    True

In [27]:
import pandas as pd

data = {
    'employee': ['Riya', 'Anand', 'Karan', 'Tanvi', 'Dev', 'Anjali'],
    'department': ['Tech', 'HR', 'Finance', 'Tech', 'HR', 'Finance'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai'],
    'salary': [75000, 30000, 45000, 80000, 32000, 50000],
    'experience': [3, 1, 4, 5, 2, 3]
}

df = pd.DataFrame(data)
df

  employee department    city  salary  experience
0     Riya       Tech    Pune   75000           3
1    Anand         HR  Mumbai   30000           1
2    Karan    Finance   Delhi   45000           4
3    Tanvi       Tech    Pune   80000           5
4      Dev         HR  Nagpur   32000           2
5   Anjali    Finance  Mumbai   50000           3

3 Quick tasks:

Average salary by department
Filter Tech or Finance employees with salary above 60000
Which employee has the highest experience?

In [28]:
df.groupby("department")["salary"].mean()

department
Finance    47500.0
HR         31000.0
Tech       77500.0
Name: salary, dtype: float64

In [29]:
df[(df["department"].isin(["Tech", "Finance"])) & (df["salary"] > 60000)]

  employee department  city  salary  experience
0     Riya       Tech  Pune   75000           3
3    Tanvi       Tech  Pune   80000           5

In [30]:
df.loc[df["experience"].idxmax() , "employee"]

'Tanvi'

In [31]:
data = {'name': ['Riya','Karan','Tanvi'], 'marks': [88,45,91]}
df = pd.DataFrame(data)
df

    name  marks
0   Riya     88
1  Karan     45
2  Tanvi     91

In [32]:
df[df['marks']>50]

    name  marks
0   Riya     88
2  Tanvi     91

In [33]:
import pandas as pd

data = {
    'name': ['Riya', 'Karan', 'Tanvi', 'Dev', 'Anjali'],
    'city': ['Pune', 'Mumbai', 'Pune', 'Delhi', 'Mumbai'],
    'score': [88, 45, 91, 67, 78],
    'passed': [True, False, True, True, True]
}

df = pd.DataFrame(data)
df

     name    city  score  passed
0    Riya    Pune     88    True
1   Karan  Mumbai     45   False
2   Tanvi    Pune     91    True
3     Dev   Delhi     67    True
4  Anjali  Mumbai     78    True

3 quick tasks:
Filter passed students from Pune or Mumbai
Average score by city
Who scored highest?

In [34]:
#1
df[df['city'].isin(['Pune' , 'Mumbai'])]

     name    city  score  passed
0    Riya    Pune     88    True
1   Karan  Mumbai     45   False
2   Tanvi    Pune     91    True
4  Anjali  Mumbai     78    True

In [35]:
#2
df.groupby('city')['score'].mean()

city
Delhi     67.0
Mumbai    61.5
Pune      89.5
Name: score, dtype: float64

In [36]:
#3
df.loc[df['score'].idxmax(), 'name']

'Tanvi'

In [37]:
import pandas as pd

data = {
    'flavor': ['Vanilla', 'Chocolate', 'Vanilla', 'Mango', 'Chocolate', 'Mango', 'Vanilla', 'Mango'],
    'day': ['Mon', 'Mon', 'Tue', 'Tue', 'Wed', 'Wed', 'Thu', 'Thu'],
    'scoops_sold': [20, 35, 15, 40, 30, 25, 18, 45],
    'price_per_scoop': [50, 60, 50, 70, 60, 70, 50, 70]
}

df = pd.DataFrame(data)
df

      flavor  day  scoops_sold  price_per_scoop
0    Vanilla  Mon           20               50
1  Chocolate  Mon           35               60
2    Vanilla  Tue           15               50
3      Mango  Tue           40               70
4  Chocolate  Wed           30               60
5      Mango  Wed           25               70
6    Vanilla  Thu           18               50
7      Mango  Thu           45               70

Tasks:

Find total scoops sold per flavor
Find average price per flavor

In [38]:
#1
df.groupby("flavor")["scoops_sold"].sum()

flavor
Chocolate     65
Mango        110
Vanilla       53
Name: scoops_sold, dtype: int64

In [39]:
df.groupby('flavor')["price_per_scoop"].mean()

flavor
Chocolate    60.0
Mango        70.0
Vanilla      50.0
Name: price_per_scoop, dtype: float64

In [40]:
import pandas as pd

data = {
    'name': ['Riya', 'Anand', 'Karan', 'Tanvi', 'Dev', 'Anjali', 'Rohan', 'Sneha'],
    'department': ['Tech', 'HR', 'Finance', 'Tech', 'HR', 'Finance', 'Tech', 'HR'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai', 'Delhi', 'Nagpur'],
    'salary': [75000, 30000, 45000, 80000, 32000, 50000, 70000, 28000],
    'experience': [3, 1, 4, 5, 2, 3, 4, 1]
}

df = pd.DataFrame(data)
df

     name department    city  salary  experience
0    Riya       Tech    Pune   75000           3
1   Anand         HR  Mumbai   30000           1
2   Karan    Finance   Delhi   45000           4
3   Tanvi       Tech    Pune   80000           5
4     Dev         HR  Nagpur   32000           2
5  Anjali    Finance  Mumbai   50000           3
6   Rohan       Tech   Delhi   70000           4
7   Sneha         HR  Nagpur   28000           1

3 tasks:

Average salary by department
Filter Tech employees with experience above 3
Who has the highest salary? (name only)

In [41]:
#1
df.groupby('department')['salary'].mean()

department
Finance    47500.0
HR         30000.0
Tech       75000.0
Name: salary, dtype: float64

In [42]:
#2
df[(df["department"] == 'Tech') & (df["experience"] > 3)]

    name department   city  salary  experience
3  Tanvi       Tech   Pune   80000           5
6  Rohan       Tech  Delhi   70000           4

In [43]:
#3
df.loc[df["salary"].idxmax(),"name"]

'Tanvi'

In [44]:
import pandas as pd

data = {
    'student': ['Riya', 'Anand', 'Karan', 'Tanvi', 'Dev', 'Anjali', 'Rohan', 'Sneha'],
    'branch': ['CS', 'IT', 'CS', 'AIML', 'IT', 'AIML', 'CS', 'IT'],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Nagpur', 'Mumbai', 'Delhi', 'Nagpur'],
    'cgpa': [8.5, 6.2, 9.1, 7.8, 6.5, 8.9, 7.2, 9.3],
    'backlogs': [0, 2, 0, 1, 3, 0, 1, 0]
}

df = pd.DataFrame(data)
df

  student branch    city  cgpa  backlogs
0    Riya     CS    Pune   8.5         0
1   Anand     IT  Mumbai   6.2         2
2   Karan     CS   Delhi   9.1         0
3   Tanvi   AIML    Pune   7.8         1
4     Dev     IT  Nagpur   6.5         3
5  Anjali   AIML  Mumbai   8.9         0
6   Rohan     CS   Delhi   7.2         1
7   Sneha     IT  Nagpur   9.3         0

3 tasks:

Average CGPA by branch
Filter students with no backlogs and CGPA above 8.0
Which city has the highest average CGPA?

In [45]:
#1
avg_cgpa = df.groupby('branch')['cgpa'].mean()
avg_cgpa

branch
AIML    8.350000
CS      8.266667
IT      7.333333
Name: cgpa, dtype: float64

In [46]:
#2
df[(df['backlogs'] == 0) & (df['cgpa'] > 8.0)]

  student branch    city  cgpa  backlogs
0    Riya     CS    Pune   8.5         0
2   Karan     CS   Delhi   9.1         0
5  Anjali   AIML  Mumbai   8.9         0
7   Sneha     IT  Nagpur   9.3         0

In [47]:
df.groupby('city')['cgpa'].mean().idxmax()

'Delhi'

In [48]:
data = {
    'intern': ['Riya', 'Anand', 'Karan', 'Tanvi', 'Dev', 'Anjali'],
    'company': ['Infosys', 'TCS', 'Wipro', 'Infosys', 'TCS', 'Wipro'],
    'city': ['Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune', 'Delhi'],
    'stipend': [15000, 12000, 10000, 18000, 11000, 9000],
    'duration_months': [2, 3, 2, 3, 2, 3]
}

df = pd.DataFrame(data)
df

   intern  company    city  stipend  duration_months
0    Riya  Infosys  Mumbai    15000                2
1   Anand      TCS    Pune    12000                3
2   Karan    Wipro   Delhi    10000                2
3   Tanvi  Infosys  Mumbai    18000                3
4     Dev      TCS    Pune    11000                2
5  Anjali    Wipro   Delhi     9000                3

3 tasks:

Average stipend by company
Filter interns at Infosys with stipend above 14000
Which city has highest average stipend?

In [49]:
#1
df.groupby('company')['stipend'].mean()

company
Infosys    16500.0
TCS        11500.0
Wipro       9500.0
Name: stipend, dtype: float64

In [50]:
#2
df[(df['company'] == 'Infosys') & (df['stipend'] >14000)]

  intern  company    city  stipend  duration_months
0   Riya  Infosys  Mumbai    15000                2
3  Tanvi  Infosys  Mumbai    18000                3

In [51]:
#3
df.groupby('city')['stipend'].mean().idxmax()

'Mumbai'

In [52]:
import pandas as pd

data = {
    'movie': ['KGF', 'RRR', 'Pushpa', 'Pathaan', 'Jawan', 'Animal', 'Kalki', 'Stree2'],
    'language': ['Kannada', 'Telugu', 'Telugu', 'Hindi', 'Hindi', 'Hindi', 'Telugu', 'Hindi'],
    'box_office_cr': [1200, 1100, 350, 1050, 1150, 900, 1000, 620],
    'rating': [8.2, 7.8, 7.5, 5.9, 6.8, 6.5, 7.1, 8.5],
    'year': [2022, 2022, 2021, 2023, 2023, 2023, 2024, 2024]
}

df = pd.DataFrame(data)
df

     movie language  box_office_cr  rating  year
0      KGF  Kannada           1200     8.2  2022
1      RRR   Telugu           1100     7.8  2022
2   Pushpa   Telugu            350     7.5  2021
3  Pathaan    Hindi           1050     5.9  2023
4    Jawan    Hindi           1150     6.8  2023
5   Animal    Hindi            900     6.5  2023
6    Kalki   Telugu           1000     7.1  2024
7   Stree2    Hindi            620     8.5  2024

3 tasks:

Which language has highest average box office collection?
Filter movies with rating above 7.5 released after 2021
Which movie made the highest collection? (movie name only)

In [53]:
df.groupby('language')['box_office_cr'].mean().idxmax()

'Kannada'

In [54]:
df[(df['rating'] > 7.5) & (df['year'] > 2021)]

    movie language  box_office_cr  rating  year
0     KGF  Kannada           1200     8.2  2022
1     RRR   Telugu           1100     7.8  2022
7  Stree2    Hindi            620     8.5  2024

In [55]:
df.loc[df['box_office_cr'].idxmax(), 'movie']

'KGF'

In [56]:
import pandas as pd

data = {
    'player': ['Virat', 'Rohit', 'Bumrah', 'Dhoni', 'Jadeja', 'Hardik', 'Gill', 'Siraj'],
    'role': ['Batsman', 'Batsman', 'Bowler', 'Wicketkeeper', 'AllRounder', 'AllRounder', 'Batsman', 'Bowler'],
    'matches': [150, 140, 80, 200, 160, 100, 60, 70],
    'runs': [7000, 6500, 500, 8000, 3000, 2500, 2000, 300],
    'avg_score': [52.3, 48.1, 8.2, 44.5, 32.1, 28.5, 38.2, 6.5]
}

df = pd.DataFrame(data)
df

   player          role  matches  runs  avg_score
0   Virat       Batsman      150  7000       52.3
1   Rohit       Batsman      140  6500       48.1
2  Bumrah        Bowler       80   500        8.2
3   Dhoni  Wicketkeeper      200  8000       44.5
4  Jadeja    AllRounder      160  3000       32.1
5  Hardik    AllRounder      100  2500       28.5
6    Gill       Batsman       60  2000       38.2
7   Siraj        Bowler       70   300        6.5

3 tasks:

Average runs by role
Filter Batsmen with avg_score above 45
Which player has played most matches?

In [57]:
#1
df.groupby('role')['runs'].mean()

role
AllRounder      2750.000000
Batsman         5166.666667
Bowler           400.000000
Wicketkeeper    8000.000000
Name: runs, dtype: float64

In [58]:
#2
df[(df['role'] == 'Batsman') & (df['avg_score'] > 45)]

  player     role  matches  runs  avg_score
0  Virat  Batsman      150  7000       52.3
1  Rohit  Batsman      140  6500       48.1

In [63]:
#3
df.loc[df['matches'].idxmax() , 'player']

'Dhoni'