In [1]:
import pandas as pd
from io import StringIO

data = """name,age,city,salary,department,experience
Rahul,28,Mumbai,55000,IT,3
Priya,34,Pune,72000,HR,8
Amit,,Delhi,48000,IT,2
Sneha,26,Bangalore,61000,Finance,4
Rohit,31,Mumbai,,IT,6
Kavya,29,Pune,53000,HR,4
Arjun,45,Delhi,95000,Finance,20
Neha,28,,67000,IT,5
Vikram,38,Mumbai,88000,HR,12
Pooja,24,Pune,42000,Finance,1
Kiran,,Bangalore,71000,IT,7
Rahul,33,Delhi,59000,,8
"""

df = pd.read_csv(StringIO(data))

In [4]:
df

      name   age       city   salary department  experience
0    Rahul  28.0     Mumbai  55000.0         IT           3
1    Priya  34.0       Pune  72000.0         HR           8
2     Amit   NaN      Delhi  48000.0         IT           2
3    Sneha  26.0  Bangalore  61000.0    Finance           4
4    Rohit  31.0     Mumbai      NaN         IT           6
5    Kavya  29.0       Pune  53000.0         HR           4
6    Arjun  45.0      Delhi  95000.0    Finance          20
7     Neha  28.0        NaN  67000.0         IT           5
8   Vikram  38.0     Mumbai  88000.0         HR          12
9    Pooja  24.0       Pune  42000.0    Finance           1
10   Kiran   NaN  Bangalore  71000.0         IT           7
11   Rahul  33.0      Delhi  59000.0        NaN           8

### **Performing EDA**

In [6]:
#1)
df.shape # tells us that we have 12 rows and 6 columns in our dataset

(12, 6)

In [15]:
#2)
df.head() # defualt it is set to five rows but we can modify it according to our needs we can take 1 row or all rows

    name   age       city   salary department  experience
0  Rahul  28.0     Mumbai  55000.0         IT           3
1  Priya  34.0       Pune  72000.0         HR           8
2   Amit   NaN      Delhi  48000.0         IT           2
3  Sneha  26.0  Bangalore  61000.0    Finance           4
4  Rohit  31.0     Mumbai      NaN         IT           6

In [20]:
#3)
df.tail() #defualt it is set to five rows but we can modify it according to our needs we can take 1 row or all rows

      name   age       city   salary department  experience
7     Neha  28.0        NaN  67000.0         IT           5
8   Vikram  38.0     Mumbai  88000.0         HR          12
9    Pooja  24.0       Pune  42000.0    Finance           1
10   Kiran   NaN  Bangalore  71000.0         IT           7
11   Rahul  33.0      Delhi  59000.0        NaN           8

In [28]:
#4)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        12 non-null     str
 1   age         10 non-null     float64
 2   city        11 non-null     str
 3   salary      11 non-null     float64
 4   department  11 non-null     str
 5   experience  12 non-null     int64
dtypes: float64(2), int64(1), str(3)
memory usage: 871.0 bytes

In [27]:
#5)
df.describe()

             age        salary  experience
count  10.000000     11.000000   12.000000
mean   31.600000  64636.363636    6.666667
std     6.239658  16218.956361    5.175701
min    24.000000  42000.000000    1.000000
25%    28.000000  54000.000000    3.750000
50%    30.000000  61000.000000    5.500000
75%    33.750000  71500.000000    8.000000
max    45.000000  95000.000000   20.000000

In [26]:
#7)
df.columns

Index(['name', 'age', 'city', 'salary', 'department', 'experience'], dtype='str')

In [25]:
#8)
df.dtypes

name              str
age           float64
city              str
salary        float64
department        str
experience      int64
dtype: object

In [38]:
#9) 
df.isnull().sum()

name          0
age           0
city          1
salary        1
department    1
experience    0
dtype: int64

In [36]:
#10)
df["age"]=df["age"].fillna(df["age"].mean())
df  #age of  2nd and 10th value got replaced by mean of 10 values which is 31.6

      name   age       city   salary department  experience
0    Rahul  28.0     Mumbai  55000.0         IT           3
1    Priya  34.0       Pune  72000.0         HR           8
2     Amit  31.6      Delhi  48000.0         IT           2
3    Sneha  26.0  Bangalore  61000.0    Finance           4
4    Rohit  31.0     Mumbai      NaN         IT           6
5    Kavya  29.0       Pune  53000.0         HR           4
6    Arjun  45.0      Delhi  95000.0    Finance          20
7     Neha  28.0        NaN  67000.0         IT           5
8   Vikram  38.0     Mumbai  88000.0         HR          12
9    Pooja  24.0       Pune  42000.0    Finance           1
10   Kiran  31.6  Bangalore  71000.0         IT           7
11   Rahul  33.0      Delhi  59000.0        NaN           8

In [39]:
df["salary"] = df["salary"].fillna(df["salary"].median())
df

      name   age       city   salary department  experience
0    Rahul  28.0     Mumbai  55000.0         IT           3
1    Priya  34.0       Pune  72000.0         HR           8
2     Amit  31.6      Delhi  48000.0         IT           2
3    Sneha  26.0  Bangalore  61000.0    Finance           4
4    Rohit  31.0     Mumbai  61000.0         IT           6
5    Kavya  29.0       Pune  53000.0         HR           4
6    Arjun  45.0      Delhi  95000.0    Finance          20
7     Neha  28.0        NaN  67000.0         IT           5
8   Vikram  38.0     Mumbai  88000.0         HR          12
9    Pooja  24.0       Pune  42000.0    Finance           1
10   Kiran  31.6  Bangalore  71000.0         IT           7
11   Rahul  33.0      Delhi  59000.0        NaN           8

In [40]:
df["city"] = df["city"].fillna(df["city"].mode()[0])
df

      name   age       city   salary department  experience
0    Rahul  28.0     Mumbai  55000.0         IT           3
1    Priya  34.0       Pune  72000.0         HR           8
2     Amit  31.6      Delhi  48000.0         IT           2
3    Sneha  26.0  Bangalore  61000.0    Finance           4
4    Rohit  31.0     Mumbai  61000.0         IT           6
5    Kavya  29.0       Pune  53000.0         HR           4
6    Arjun  45.0      Delhi  95000.0    Finance          20
7     Neha  28.0      Delhi  67000.0         IT           5
8   Vikram  38.0     Mumbai  88000.0         HR          12
9    Pooja  24.0       Pune  42000.0    Finance           1
10   Kiran  31.6  Bangalore  71000.0         IT           7
11   Rahul  33.0      Delhi  59000.0        NaN           8

In [41]:
print(df["city"].mode())

0    Delhi
Name: city, dtype: str