In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## **1. EDA**

In [3]:
df.shape

(8807, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 3.9 MB

In [5]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [6]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [7]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

## **2. Data Cleaning**

In [8]:
# coverting the date column to actual date column 
df['date_added'] = pd.to_datetime(df['date_added'], format='mixed')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   datetime64[us]
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: datetime64[us](1), int64(1), str(10)
memory usage: 3.7 MB

In [10]:
# handeling missing values 
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df.dropna(subset = ["date_added" , "rating" , "duration"] , inplace = True)

In [11]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

## **1. Count how many Movies vs TV Shows are there**

In [12]:
df["type"].value_counts()

type
Movie      6126
TV Show    2664
Name: count, dtype: int64

## **2. Which country has produced the most content?**

In [13]:
df['country'].value_counts().head(1)

country
United States    2809
Name: count, dtype: int64

## **3. Filter all content released after 2018 that is rated TV-MA**

In [14]:
df[(df["rating"] == "TV-MA") & (df["release_year"] > 2018)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",Unknown,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8437,s8438,TV Show,The Netflix Afterparty,Unknown,"David Spade, London Hughes, Fortune Feimster",United States,2021-01-02,2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London..."
8516,s8517,Movie,The Spy Who Fell to Earth,Thomas Meadmore,Unknown,United Kingdom,2019-04-05,2019,TV-MA,94 min,"Documentaries, International Movies","Based on Dr. Ahron Bregman's book, this docume..."
8631,s8632,Movie,Trixie Mattel: Moving Parts,Nicholas Zeig-Owens,Brian Firkus,United States,2020-03-27,2019,TV-MA,91 min,"Documentaries, Music & Musicals",Drag queen Trixie Mattel deals with the bitter...
8718,s8719,Movie,Westside vs. the World,Michael Fahey,"Ron Perlman, Louie Simmons",Unknown,2019-08-09,2019,TV-MA,96 min,"Documentaries, Sports Movies",A look into the journey of influential strengt...
8756,s8757,Movie,Woodstock,Barak Goodman,Unknown,United States,2019-08-13,2019,TV-MA,97 min,"Documentaries, Music & Musicals",For the 50th anniversary of the legendary Wood...

## **4. Filter all Movies from India only**

In [15]:
df[(df["country"] == "India") & (df["type"] == "Movie")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
105,s106,Movie,Angamaly Diaries,Lijo Jose Pellissery,"Antony Varghese, Reshma Rajan, Binny Rinky Ben...",India,2021-09-05,2017,TV-14,128 min,"Action & Adventure, Comedies, Dramas",After growing up amidst the gang wars of his h...
114,s115,Movie,Anjaam,Rahul Rawail,"Madhuri Dixit, Shah Rukh Khan, Tinnu Anand, Jo...",India,2021-09-02,1994,TV-14,143 min,"Dramas, International Movies, Thrillers",A wealthy industrialist’s dangerous obsession ...
116,s117,Movie,Dhanak,Nagesh Kukunoor,"Krrish Chhabria, Hetal Gada, Vipin Sharma, Gul...",India,2021-09-02,2015,TV-PG,114 min,"Comedies, Dramas, Independent Movies",A movie-loving 10-year-old and her blind littl...
118,s119,Movie,Gurgaon,Shanker Raman,"Akshay Oberoi, Pankaj Tripathi, Ragini Khanna,...",India,2021-09-02,2017,TV-14,106 min,"Dramas, International Movies, Thrillers",When the daughter of a wealthy family returns ...
...,...,...,...,...,...,...,...,...,...,...,...,...
8772,s8773,Movie,Yamla Pagla Deewana 2,Sangeeth Sivan,"Dharmendra, Sunny Deol, Bobby Deol, Neha Sharm...",India,2017-05-01,2013,TV-14,147 min,"Action & Adventure, Comedies, International Mo...","Up to his old tricks, con man Dharam poses as ..."
8773,s8774,Movie,Yanda Kartavya Aahe,Kedar Shinde,"Ankush Choudhary, Smita Shewale, Mohan Joshi, ...",India,2018-01-01,2006,TV-PG,151 min,"Comedies, Dramas, International Movies",Thanks to an arranged marriage that was design...
8798,s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,2019-12-31,2014,TV-MA,131 min,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...
8799,s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,2018-02-15,2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

## **5. Filter titles where director contains the name "Shah"**

In [16]:
df[df["director"].str.contains("Shah")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1410,s1411,Movie,Tribhanga - Tedhi Medhi Crazy,Renuka Shahane,"Kajol, Tanvi Azmi, Mithila Palkar, Kunaal Roy ...",India,2021-01-15,2021,TV-MA,96 min,"Dramas, International Movies","When her estranged mother falls into a coma, a..."
2544,s2545,Movie,Action Replayy,Vipul Amrutlal Shah,"Akshay Kumar, Aishwarya Rai Bachchan, Om Puri,...",India,2020-05-11,2010,TV-PG,129 min,"Children & Family Movies, Comedies, Internatio...","Sick of his parents’ constant squabbling, a yo..."
2644,s2645,Movie,"Yours Sincerely, Kanan Gill",Neville Shah,Kanan Gill,India,2020-04-24,2020,TV-MA,72 min,Stand-Up Comedy,Revisiting life goals set in a letter written ...
2729,s2730,Movie,Kaal,Soham Shah,"Ajay Devgn, Vivek Oberoi, John Abraham, Lara D...",India,2020-04-01,2005,TV-14,126 min,"Horror Movies, International Movies, Thrillers","Trapped in a national park, a tiger expert and..."
3868,s3869,Movie,Laatu,Manav Shah,"Gagan Kokri, Aditi Sharma, Karamjit Anmol, Sar...",India,2019-05-02,2018,TV-PG,116 min,"Comedies, Dramas, International Movies",A man who hopes to bring light to his village ...
4615,s4616,Movie,Zindagi Kitni Haseen Hay,Anjum Shahzad,"Feroze Khan, Sajal Ali, Jibrayl Ahmed Rajput, ...",Pakistan,2018-10-01,2016,TV-14,126 min,"Dramas, International Movies, Romantic Movies",Two young parents struggle to keep their marri...
4797,s4798,Movie,Namastey London,Vipul Amrutlal Shah,"Akshay Kumar, Katrina Kaif, Rishi Kapoor, Upen...",India,2018-07-01,2007,TV-14,130 min,"Comedies, Dramas, International Movies","To her Indian parents' dismay, London-born Jas..."
5482,s5483,Movie,Kabhi Haan Kabhi Naa,Kundan Shah,"Shah Rukh Khan, Suchitra Krishnamoorthi, Deepa...",India,2017-05-15,1994,TV-14,151 min,"Comedies, Dramas, International Movies",A dreamer falls for a girl who is in love with...
6610,s6611,Movie,Dil Hai Tumhaara,Kundan Shah,"Rekha, Preity Zinta, Mahima Chaudhry, Arjun Ra...",India,2018-04-01,2002,TV-14,176 min,"Dramas, International Movies, Music & Musicals",The sophisticated son of a powerful businessma...
7247,s7248,Movie,Kya Kehna,Kundan Shah,"Preity Zinta, Saif Ali Khan, Anupam Kher, Fari...",India,2018-04-01,2000,TV-PG,149 min,"Dramas, International Movies, Romantic Movies",A young university student's world is shaken a...
7688,s7689,Movie,P Se PM Tak,Kundan Shah,"Meenakshi Dixit, Indrajeet Soni, Bharat Jadhav...",India,2018-08-01,2015,TV-14,117 min,"Comedies, Independent Movies, International Mo...",A prostitute who is down on her luck gets caug...

## **6. What are the top 5 most common ratings in the dataset?**

In [17]:
df['rating'].value_counts().head(5)

rating
TV-MA    3205
TV-14    2157
TV-PG     861
R         799
PG-13     490
Name: count, dtype: int64

## **7. Find the top 5 countries with most content (Movies + TV shows combined)**

In [19]:
df["country"].value_counts().head(5)

country
United States     2809
India              972
Unknown            829
United Kingdom     418
Japan              243
Name: count, dtype: int64

## **8. Which year had the highest number of releases?**

In [24]:
df["release_year"].value_counts().head(1)

release_year
2018    1146
Name: count, dtype: int64

## **9.Create a new column duration_type — for Movies it should say Movie and for TV Shows it should say based**
## **on number of seasons (Hint: you'll need to look at the duration column format)**

In [ ]:
df["duration_type"] =

## **10. Filter all titles where genre (listed_in) contains the word "Comedy"**

In [22]:
df[df["listed_in"].str.contains("Comedy")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
278,s279,Movie,Lokillo: Nothing's the Same,Julián Gaviria,Lokillo Florez,Colombia,2021-08-12,2021,TV-MA,64 min,Stand-Up Comedy,"Through songs and puns, comedian Lokillo Flore..."
359,s360,Movie,The Original Kings of Comedy,Spike Lee,"Steve Harvey, D.L. Hughley, Cedric the Enterta...",United States,2021-08-01,2000,R,111 min,Stand-Up Comedy,"Comedians Steve Harvey, Cedric the Entertainer..."
388,s389,TV Show,Plastic Cup Boyz: Laughing My Mask Off!,"Royale Watkins, Rich Schlansker","Joey Wells, Will 'Spank' Horton, Na'im Lynn",Unknown,2021-07-27,2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies",Comedy collective The Plastic Cup Boyz pour ou...
400,s401,TV Show,Revelations: The Masters of the Universe: Reve...,Unknown,"Kevin Smith, Tiffany Smith, Robert David, Sara...",Unknown,2021-07-23,2021,TV-PG,1 Season,"Anime Series, Stand-Up Comedy & Talk Shows",Take a behind-the-scenes look at “Masters of t...
475,s476,Movie,The Stand-Up,Daniel Růžička,"Iva Pazderková, Lukáš Pavlásek, Daniel Čech, P...",Unknown,2021-07-10,2019,TV-MA,93 min,Stand-Up Comedy,Members of the comedy group Na Stojáka take th...
...,...,...,...,...,...,...,...,...,...,...,...,...
7812,s7813,TV Show,Queens of Comedy,Unknown,Unknown,Unknown,2018-05-01,2017,TV-MA,1 Season,"International TV Shows, Stand-Up Comedy & Talk...",Eight women perform in front of celebrity judg...
7813,s7814,TV Show,Queens vs. Kings,Unknown,"Varun Thakur, Anu Menon, Rahul Subramanian, Si...",Unknown,2018-10-25,2018,TV-14,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","No ""ism"" is left unturned in this celebrity ga..."
7908,s7909,TV Show,Russell Peters vs. the World,Unknown,Russell Peters,United States,2013-10-14,2013,NR,1 Season,"Docuseries, Stand-Up Comedy & Talk Shows","A four-part docu-series that's an exclusive, b..."
7909,s7910,Movie,Russell Peters: Notorious,Dave Higby,Russell Peters,United States,2013-10-14,2013,NR,72 min,Stand-Up Comedy,Global comedy star Russell Peters leaves no et...
8437,s8438,TV Show,The Netflix Afterparty,Unknown,"David Spade, London Hughes, Fortune Feimster",United States,2021-01-02,2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London..."

## **11.Group by type and find average release_year for Movies vs TV Shows — which one is generally newer content?**

In [23]:
df.groupby("type")["release_year"].mean()

type
Movie      2013.120144
TV Show    2016.627628
Name: release_year, dtype: float64